config/initializers/mime_types.rb

`.mp4` や `.webm`, `.ogv` をコンテンツに埋め込むと IE9/10/11 では、"無効なソース" と表示され正しく再生されない。原因は CMS コンテンツの静的ファイルが `send_file` によってレスポンスされる際、未定義の拡張子のため ContentType が `application/octet-stream` にセットされるため（`send_file` の `:type` オプションの初期値は `application/octet-stream`）。
http://blogs.msdn.com/b/thebeebs/archive/2011/07/20/html5-video-not-working-in-ie9-some-tips-to-debug.aspx
なお、Chrome/Firefox/Safari では `application/octet-stream` でも問題なく再生される。
動画を埋め込む場合 `<video>` タグで `.mp4` や `.webm`, `.ogv` を使うのが一般的だと思うので SHIRASAGI で対応しておいても良いと思います。

Fix video dose not play in IE9 or later

---

.gitignore

IntelliJ IDEA と RubyMine のプロジェクトファイルとワークファイルを無視する設定を .gitignore に追加しました。
参考:
* https://www.gitignore.io/
* https://www.gitignore.io/api/intellij

add project and work files of IntelliJ IDEA & RubyMine to .gitignore.

---

.coveralls.yml

Travis Ci で次のようなエラーが発生しています。
```
Coveralls encountered an exception:
RestClient::UnprocessableEntity
422 Unprocessable Entity
/home/travis/.rvm/gems/ruby-2.1.2/gems/rest-client-1.7.2/lib/restclient/abstract_response.rb:48:in `return!'
/home/travis/.rvm/gems/ruby-2.1.2/gems/rest-client-1.7.2/lib/restclient/request.rb:495:in `process_result'
/home/travis/.rvm/gems/ruby-2.1.2/gems/rest-client-1.7.2/lib/restclient/request.rb:421:in `block in transmit'
/home/travis/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/http.rb:853:in `start'
/home/travis/.rvm/gems/ruby-2.1.2/gems/rest-client-1.7.2/lib/restclient/request.rb:413:in `transmit'
/home/travis/.rvm/gems/ruby-2.1.2/gems/rest-client-1.7.2/lib/restclient/request.rb:176:in `execute'
/home/travis/.rvm/gems/ruby-2.1.2/gems/rest-client-1.7.2/lib/restclie …
```

[WIP PR] Study and Fix Travis Ci's UnprocessableEntity Error.

---

spec/spec_helper.rb

テストを実行すると、coverage ディレクトリに index.html が生成されるようになり、index.html をブラウザで開くとコードカバレッジを閲覧できるようにしてみました。

add simplecov's html formatter.

---

app/models/ezine/page.rb

Fix that a sent log is created also on test delivery.
配信ログがテスト配信でも作成されるようになっていたのを修正

Enable to switch creating a sent log or not.

---

app/models/ezine/addon.rb
app/models/ezine/page.rb
app/views/ezine/agents/addons/page/body/_form.html.erb
app/views/ezine/agents/addons/page/body/_show.html.erb
app/views/ezine/agents/addons/page/body/view/index.html.erb
app/views/ezine/agents/pages/page/index.html.erb
app/views/ezine/pages/_form.html.erb
app/views/ezine/pages/_show.html.erb
config/locales/ezine/ja.yml

#131 の
> ・記事詳細画面
> 　本文が表示されません。
に対応しつつ，`Ezine::Page` の body 的である部分，`html` フィールドと `text` フィールドを `Ezine::Addon::Page::Body` に切り出し，view も分割しました．

Show Ezine::Page body (html and text) on public view

---

app/models/ezine/member.rb
app/models/ezine/page.rb
app/models/ezine/test_member.rb

Refactor `Ezine::Page#deliver_to` argument specification.
```
・コードレビュー：
　deliver_to メソッド、引数渡しで分岐している点を要検討
```
ref. https://www.facebook.com/groups/ssproj/permalink/821120054628656/
`is_test` という引数で判断はオブジェクト指向的にはどうなの？

Refactor Ezine::Page#deliver_to argument

---

bin/unicorn.sh

bin/unicorn.shでユニコーン起動時に、tmp/pids/unicorn.pid が残っている場合に起動しない現象に対応。
unicorn.pidが存在する場合、ファイルに記録されているpidのunicorn masterプロセスを確認し、
プロセスが存在しない場合は、同ファイルを削除し起動を行う対応としました。
(修正)
・unicorn masterプロセスを確認の際、grep "unicorn" | grep "master"で確認
・cat, grepのエラー出力を考慮し、2>&1 の記述を削除

fix unicorn startup file

---

app/controllers/ezine/members_controller.rb
app/controllers/ezine/pages_controller.rb
app/controllers/ezine/test_members_controller.rb
app/models/ezine/member.rb
app/models/ezine/member_searchable.rb
app/models/ezine/page.rb
app/models/ezine/test_member.rb
app/views/ezine/members/_delete.html.erb
app/views/ezine/members/_form.html.erb
app/views/ezine/members/_menu.html.erb
app/views/ezine/members/_show.html.erb
app/views/ezine/members/index.html.erb
app/views/ezine/pages/index.html.erb
app/views/ezine/test_members/index.html.erb
config/locales/ezine/ja.yml
config/routes/ezine/routes.rb

* Add search function to `Ezine::Member` and `Ezine::Testmember`
* Remove `preview_text` method
* Add deliver start time in `ezine/pages/index`
* Modify `Ezine::Member` to editable
* Add `state` field
* Add its views and locales
* Fix `Ezine::Page#members_to_deliver`
* Add validations of `email_type` and `state`
For #195 following issues.
> 管理画面からメルマガ読者を削除（無効）にできるようにしてください。
> エラーメールなどを確認して削除したいのと、管理者が削除したことがわかるよ
> うにしたいです。
> 削除するため、検索機能をつけてください。
and
> 本配信の履歴がわかるようにしてください。
> 一覧で、いつ配信したかわかるようにしてください。

Fix ezine management view

---

app/models/ezine/page.rb
app/views/ezine/pages/index.html.erb
config/locales/ezine/ja.yml

To show test delivery log datetime in management views.
For the below issue of #195.
> テスト配信の履歴がわかるようにしてください。

Add test_delivered to Ezine::Page

---

config/initializers/ss/rb_config.rb

Remove `Config` constant only when it is defined.
Fix the following error
```
config/initializers/ss/rb_config.rb:2:in `remove_const': constant Object::Config not defined (NameError)
```
Ruby 2.2.0 で動かそうとした場合に発生するエラーに対処するためだけのコードです．テストをTravisCI先生に見てもらいたいのでPR作ってみます．
http://stackoverflow.com/questions/10171978/check-if-a-constant-is-already-defined

Fix for Ruby 2.2.0

---

app/controllers/cms/preview_controller.rb

プレビュー表示にてサイトトップのリンクが公開画面になってしまう #243

fix: link to root in preview

---

app/models/ss/config.rb
spec/models/ss/config_spec.rb

* SS::Config always new OpenStruct. this is inefficient.
* In SS::Config.env, data[:env] returns always nil because name is undefined and "data[name] = OpenStruct.new(conf)" statement meaningless.

SS::Config performance improments.

---

app/models/chorg/substituter.rb
spec/models/chorg/substituter_spec.rb

* don't replace string if to_value is blank.
* In previous specification, removes string if to_value is blank.
置換先の値が blank の場合、置換しないようにした。
従前の仕様では、置換先の文字列が空の場合、それは置換元を削除するという意味で働いた。

change chorg specification.

---

spec/helpers/application_helper_spec.rb
spec/helpers/event/event_helper_spec.rb

refactor helper rspec by specifying `type: :helper` which enables rspec-rails's extensions.

refactor helper rspec

---

app/models/ss/migration.rb
lib/migrations/ezine/20150408081234_enable_member_state.rb
lib/migrations/ezine/20150423044546_update_results.rb
lib/tasks/ss/migrate.rake
spec/factories/ezine/member.rb
spec/factories/ezine/page.rb
spec/factories/ss/migrations.rb
spec/lib/ss/migrations/20150408081234_enable_member_state_spec.rb
spec/lib/ss/migrations/20150423044546_update_results_spec.rb
spec/models/ss/migration_spec.rb
spec/spec_helper.rb

`rake ss:migrate` 出来るようにしました．
ezine関連のタスクを2つ，サンプルとして実装している状態であるとします．
1つは `Ezine::Member` の `state` フィールドを `enabled` にするもの．
もう1つは `Ezine::Page` の `results` フィールドを単なる `Array` から `embeds_many` に変更するもの．

Migration for #344

---

app/models/concerns/ss/document.rb
spec/models/ss/document_spec.rb

`SS::Document` の `created` と `updated` が原理的にズレる．ごく僅かなのと丸められるのとで気にされてなかったのだと思われるが，一致して欲しいという要求が出てきそうなので修正したい．
失敗例:
```text
7: RSpec.describe Klass, type: :model, dbscope: :example do
8:   it do
9:     Timecop.scale(1_000_000_000)
10:     object = Klass.new
11:     binding.pry
=> 12:     expect(object.created == object.updated).to be_truthy
13:     Timecop.return
14:   end
15: end
[1] pry(#<RSpec::ExampleGroups::Klass>)> object.created
=> Thu, 21 May 2015 23:15:58 +0900
[2] pry(#<RSpec::ExampleGroups::Klass>)> object.updated
=> Sat, 30 May 2015 17:33:57 +0900
[3] pry(#<RSpec::ExampleGroups::Klass>)> continue
1) Klass should be truthy
Failure/Error: expect(object.created == object.updated).to be_truthy
expected: truthy value
got: false
1/1 …
```

Fix timestamp initialization

---

spec/models/ss/file_spec.rb

fix for rubocop: Extra blank line detected.

---

app/models/job/service.rb
spec/models/voice/synthesis_job_spec.rb

this error occurs:
NameError: undefined local variable or method `fatal' for main:Object

remove "e.kind_of?(fatal)" from Job::Service#system_error? because the NameError occurs

---

lib/migrations/ss/20150521192401_fix_ss_files_site_id.rb

すでにアップされている添付ファイルにsite_idを付けるmigration
以下の添付ファイルが対象
* ページの添付ファイル
* バナーの画像
* 施設の画像

add site_id in SS::File migration

---

app/controllers/concerns/cms/public_filter.rb

rspec では、HTTP_HOST のような固定的な env なら設定可能ですが、
動的に変化するような REQUEST_PATH を設定するのは難しいです。
例えば、メンバーページにログインするよう処理をテストする場合、
リダイレクトが何回か発生します。リダイレクトのたびに REQUEST_PATH を
変更する必要がありますが、rspec 側だけでは、なかなか容易に対応できません。
Cms::PublicFilter 側のサポートが必要です。

add public side rspec support.

---

Gemfile.lock

From version 1.10, this specification is added to the tail of Gemfile.lock.
ref. https://github.com/bundler/bundler/blob/master/CHANGELOG.md#1100pre2-2015-05-07

Add "BUNDLED_WITH" specification to Gemfile.lock

---

README.md

✗ `gem install bundle`
✓ `gem install bundler`

[ci skip] Fix Bundler gem name

---

app/models/concerns/ss/file/model.rb

add downcase to max_filesize_ext #392

---

app/models/workflow/addon/branch.rb

workflow branch: skip validation in clone_files

---

spec/spec_helper.rb

カバレッジの計測絡みの処理に掛かる時間が，何度も繰り返し手元で `rspec spec/foo/bar_spec.rb` を実行しているとき(※)にちょっと鬱陶しい．
(※)
- テストの書き方を模索しているとき
- FactoryGirlの書き方を模索しているとき
- 実装がよく分からず試行錯誤しているとき
CoverallsやそれにまつわるSimpleCovの処理は，開発者の手元で何度も実行する必要は無いのではないか？CIをしてくれるサービス達に後から教えてもらうだけでもいいのではないか？と思っていたのと，自分がTravisCI上で動いているのかどうかを調べることが環境変数で出来ることが分かったので今回のPull Requestを作ってみました．
ref. http://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables

Run coverage analysis only on TravisCI

---

app/models/concerns/ss/relation/thumb.rb

1. destroy_thumbs method is public
2. don't file.set() when name not change

[fix] relation thumb

---

app/models/concerns/cms/reference/role.rb

`cms_roles.site(site)`が空のときこのメソッドが`nil`を返してしまう(`[].max #=> nil` のため)．
さらに，もし`@cur_user`が全く関係のない他のモデルについてのロール(※そのロールはより高いレベルを持っている)を持っているとすると，正しくないレベルが返ってしまう．本来は関連のあるモデルについてだけのロールのレベルの最大値が返るべきである．

[fix] Cms::Reference::Role#cms_role_level not to return nil and to return correct level

---

app/models/concerns/cms/addon/list.rb
config/locales/cms/ja.yml

ループHTMLに管理グループを含めるPRです。
* `#{group}` 
先頭のグループ一つ `default_scope -> { order_by(order: 1, name: 1) }`
* `#{groups}` 
全てのグループ

[add] group keyword in list template

---

app/models/cms/member.rb

cms memberのindexに以下が追加されました。
`index({ site_id: 1, email: 1 }, { unique: true, sparse: true })`
しかし、oauthでログインするときはemailが空の場合が想定されており
テストが失敗します。
とりあえずbuildを直すために再度コメントアウトします。

[skip ci] restore member.index

---

app/assets/javascripts/ss/lib/list_ui.coffee.erb
app/controllers/concerns/cms/crud_filter.rb
app/controllers/concerns/ss/crud_filter.rb
app/controllers/uploader/files_controller.rb
app/views/ss/crud/_list_head.html.erb
config/locales/ja.yml
config/routes/ads/routes.rb
config/routes/article/routes.rb
config/routes/category/routes.rb
config/routes/chorg/routes.rb
config/routes/cms/routes_end.rb
config/routes/event/routes.rb
config/routes/ezine/routes.rb
config/routes/facility/routes.rb
config/routes/faq/routes.rb
config/routes/history/routes.rb
config/routes/inquiry/routes.rb
config/routes/job/routes.rb
config/routes/kana/routes.rb
config/routes/key_visual/routes.rb
config/routes/ldap/routes.rb
config/routes/rss/routes.rb
config/routes/sitemap/routes.rb
config/routes/sns/routes.rb
config/routes/sys/routes.rb
config/routes/urgency/routes.rb
config/routes/voice/routes.rb
config/routes/workflow/routes.rb

一括削除UIの為に `destroy_all` `action` を `crud` に追加しました。
ルーティングは以下が使えました。
<pre>
delete article/pages/:id    #destory
delete article/pages/        #destory_all
</pre>
※params[:ids]を参照します。
アップローダだけは同じアクションが使えなかったので別対応しています。

[add] destroy_all action

---

Gemfile
Gemfile.lock
config.ru

worker再起動のトリガーとなるリクエスト回数の範囲（3072-4096）はunicorn-worker-killerの初期値です。
一方、メモリ範囲(384MB-448MB)はシラサギ本番稼働中のworkerのメモリ占有平均が約258MBの為、
1.5倍程度の使用量から+64MBを再起動対象となるメモリ占有範囲としています。

[modify]add unicorn worker killer

---

app/controllers/cms/preview_controller.rb
app/models/oauth/base.rb

Raptor (Passenger 5.x) seems not to provide REQUEST_PATH env.

[fix] fallback to request.path when REQUEST_PATH env is not provided.

---

spec/spec_helper.rb

Fix the SimpleCov deprecation warning.
The warning message is below:
/path/to/shirasagi/spec/spec_helper.rb:23:in `<top (required)>': [DEPRECATION]::[] is deprecated. Use ::new instead.
ref.
- https://github.com/colszowka/simplecov#using-multiple-formatters
- https://github.com/colszowka/simplecov/issues/428
- https://github.com/colszowka/simplecov/pull/432

Fix simplecov deprecation

---

app/controllers/cms/agents/parts/crumb_controller.rb
app/controllers/concerns/cms/base_filter.rb
app/controllers/concerns/cms/public_filter/layout.rb
app/controllers/concerns/cms/public_filter/node.rb
app/models/concerns/cms/content.rb
app/models/concerns/cms/model/node.rb
app/views/gws/main/_links.html.erb

DBの問い合わせ回数を減らしてみた。
~~~
(find) collection=ss_sites selector={"_id"=>1} flags=[] limit=0 skip=0 batch_size=nil fields=nil runtime: 0.4343ms
(belongs_to) collection=ss_sites selector={"$query"=>{"_id"=>1}, "$orderby"=>{:_id=>1}} flags=[] limit=-1 skip=0 batch_size=nil fields=nil runtime: 0.4906ms
~~~
常に呼ばれるところなので Query を統一した。
~~~
@cur_site = Cms::Site.find params[:site]
@cur_site = Cms::Site.where(id: params[:site]).first # and unless condition
~~~
~~~
collection=gws_links selector={"$query"=>{"site_id"=>1, "state"=>"public", "$or"=>[{"target"=>nil}, {"target"=>"all"}, {"$and"=>[{"target"=>"group"}, {"group_ids"=>{"$in"=>[3]}}]}]}, "$orderby"=>{"released"=>-1}} flags=[] limit=-1 skip=0 batch_size=nil fields={:_id=>1} runtime: 0.5305ms
collection=gws_links selector={"$query"=>{"site_id"=>1, …

[refactor] Query tuning

---

app/controllers/concerns/mobile/public_filter.rb
app/controllers/concerns/ss/trans_sid_filter.rb
app/models/concerns/ss/addon/mobile_setting.rb
app/views/ss/agents/addons/mobile_setting/_form.html.erb
app/views/ss/agents/addons/mobile_setting/_show.html.erb
config/locales/ss/ja.yml
spec/models/cms/site_spec.rb
spec/models/ss/site_spec.rb

別案件で Trans SID の仕組みを導入してみたが、うまく動作しないので削除。
* 固定ページで Trans SID が動作しない。
* 書き出されたページで Trans SID が動作しない。
Trans SID 自体 IPA の『安全なウェブサイトの作り方』でも非推奨であり、
現状、中途半端に動作する機能となっているので Trans SID を削除する。

[delete] trans sid support

---

Gemfile
Gemfile.lock
spec/models/voice/file_spec.rb
spec/models/voice/synthesis_job_spec.rb
spec/spec_helper.rb
spec/support/ss/database_cleaner_support.rb

MongoDB 3.2 + WiredTiger (Default Storage Engine on MongoDB 3.2) + DatabaseCleaner の組み合わせがうまく動作しないことが分かりました。
https://github.com/DatabaseCleaner/database_cleaner/issues/392
DatabaseCleaner は、前にも MongoDB との相性が悪くうまく動作しないことが何度かありましたので、
DatabaseCleaner の使用をやめて、自前で Database Cleaner 相当のことを処理することにしました。
DatabaseCleaner では、全てのコレクションを削除していましたが、本プルリクではデータベースを drop するようにしたので、テストが少し早くなったと思います。

remove database clearner

---

app/controllers/gws/schedule/group_plans_controller.rb
app/controllers/gws/users_controller.rb
app/models/concerns/ss/model/user.rb
app/models/concerns/ss/model/user_title.rb
app/models/concerns/ss/reference/user_titles.rb
app/models/gws/user.rb
app/models/gws/user_title.rb
app/views/gws/users/_form.html.erb
app/views/gws/users/_show.html.erb
app/views/gws/users/index.html.erb
spec/factories/chorg/changesets.rb
spec/factories/chorg/revisions.rb
spec/factories/gws/user_titles.rb
spec/factories/gws/users.rb
spec/factories/sys/groups.rb
spec/features/cms/groups_spec.rb
spec/features/sys/db_spec.rb
spec/features/sys/groups_spec.rb
spec/features/sys/info_spec.rb
spec/features/sys/roles_spec.rb
spec/features/sys/sites_spec.rb
spec/features/sys/test_spec.rb
spec/features/sys/users_spec.rb
spec/models/chorg/substituter_spec.rb
spec/models/gws/user_title_spec.rb

役職順表示に対応しました。
課題がいくつかあります。
* 平社員（＝役職なし）が役職order を持てないため、1千万を既定でセットするようにしました。
* 全 Gws::User の再保存が必要です。
* 役職順にソートできるようになりましたが、index を使用した効率のよいソート方法が不明で、MongoDB にメモリでソートしてもらっている状態です。ユーザー数が数千を超えると、うまくソートできるのかどうか...。

user title order

---

app/assets/stylesheets/gws/style.scss
app/assets/stylesheets/ss/style.scss

Win10 Edge で prev と next が正しく表示されない問題は、以下の Issue に登録されたまま未解決です。
https://github.com/fullcalendar/fullcalendar/issues/2852
※2015/12/19 のコメントにあるように
※.fc-icon:after {margin: 0 0; color: black}
※とすると直ると思います。

スケジュールの prev と next が正しく表示されない問題の修正

---

app/models/gws/schedule/repeat_plan.rb
spec/features/gws/schedule/plans/repeated_spec.rb
spec/models/gws/schedule/repeat_plan_spec.rb

毎月第5月曜日（火曜日等でも可）にスケジュールを設定すると、内部エラーになっていたのを修正。
第5月曜日の存在しない月は、第4月曜日にスケジュールを設定するようにした。

[fix] every 5th monday schedule plan

---

app/assets/javascripts/gws/schedule/lib/calendar.coffee.erb
app/assets/javascripts/gws/schedule/lib/multiple_calendar.coffee.erb
app/assets/javascripts/ss/lib/dropdown.coffee
app/assets/javascripts/ss/lib/tree_ui.coffee
app/assets/javascripts/ss/script.coffee.erb
app/assets/stylesheets/ss/_pc_mb.scss
app/controllers/gws/apis/users_controller.rb
app/controllers/gws/schedule/facilities_controller.rb
app/controllers/gws/workflow/search_approvers_controller.rb
app/controllers/workflow/search_approvers_controller.rb
app/views/gws/apis/facilities/index.html.erb
app/views/gws/apis/users/_custom_group_dropdown.html.erb
app/views/gws/apis/users/_group_dropdown.html.erb
app/views/gws/apis/users/index.html.erb
app/views/gws/board/apis/categories/index.html.erb
app/views/gws/board/topics/index.html.erb
app/views/gws/schedule/facilities/index.html.erb
app/views/gws/share/apis/categories/index.html.erb
app/views/gws/share/files/index.html.erb
app/views/workflow/search_approvers/index.html.erb
config/locales/gws/board/ja.yml
config/locales/gws/share/ja.yml
spec/features/gws/board/topics/basic_crud_spec.rb
spec/features/gws/share/files_spec.rb
spec/features/gws/workflow/files/basic_crud_spec.rb
spec/features/workflow/routes_spec.rb
spec/features/workflow/search_approvers_spec.rb

ユーザー選択ダイアログの次の問題を修正。
* グループ数が多いと画面の下にはみ出してしまってグループが選択できない。
* スクロールバーを表示するようにしました（下図）。
* 全組織の中からユーザーを選択できない。
* ドロップダウンの先頭にグループ名を表示するようにしました（下図）。<br>グループ名を選択すると、全組織内からユーザーを選択できます。
他:
* ワークフロー経路作成時のユーザー選択もツリー表示しました。
* スマホでもテストし、スマホでも操作できるようにドロップダウンの高さを 250px としています。
* クリック範囲を通常より広げているため、スマホでも割合ストレス無く操作できました。
HTML 量の削減については、おいおい検討していきたいと思います。
※以下ぐらいの簡潔さで表示できるのが目標。
```
<%= f.tree_select :groups %>
```

unabled select group

---

.codeclimate.yml

codeclimate の仕様変更（？）により public/assets の下のファイルが、点数の判定に含まれるようになってしまっています。
それを除外する設定を書いてみました。
あわせて codeclimate は[様々な engine](https://docs.codeclimate.com/docs/list-of-engines) を有効・無効にできるようですので、Ruby に関係しそうな全てのエンジン `rubocop`, `brakeman`, `bundler-audit`, `coffeelint`, `csslint`, `duplication`, `rubymotion`, `scss-lint` を有効にしてみました。

[add] .codeclimate.yml

---

app/controllers/cms/groups_controller.rb
app/models/cms/group.rb

`Cms::Group` の `default_scope` に `active` を追加しました。
groups controller は、グループの有効・無効に関係なく、すべてを捜査対象とする必要がありますが、
この修正により groups controller が有効なグループしか捜査対象にできなくて困るので、groups controller では、default scope を無効にして group を検索するようにしました。

[modify] add criteria `active` to default scope

---

app/models/ads/node.rb
app/models/article/node.rb
app/models/category/node.rb
app/models/cms/node.rb
app/models/cms/site.rb
app/models/concerns/cms/addon/default_release_plan.rb
app/models/concerns/cms/addon/release_plan.rb
app/models/event/node.rb
app/models/ezine/node.rb
app/models/facility/node.rb
app/models/faq/node.rb
app/models/sitemap/node.rb
app/views/cms/agents/addons/default_release_plan/_form.html.erb
app/views/cms/agents/addons/default_release_plan/_show.html.erb
app/views/cms/agents/addons/release_plan/_form.html.erb
app/views/ss/agents/addons/mobile_setting/_form.html.erb
config/locales/cms/ja.yml
config/locales/ss/ja.yml
spec/features/article/pages/auth_spec.rb
spec/features/article/pages/basic_crud_spec.rb
spec/features/article/pages/default_release_plan_spec.rb
spec/features/article/pages/lock_spec.rb

公開予約の開始／終了日時にデフォルトで日付が入力されるようにする機能拡張です。
* サイトとノードの両方に公開予約の既定値を設定できるように拡張。
* サイト全体に公開予約の既定値を入力させたければ、サイトに既定値を設定する。
* 特定のノードでのみ公開予約の既定値を入力させたければ、ノードに既定値を設定する。
* サイトとノードの両方に設定がある場合、ノードの方が優先。
* ただしページは、親の設定しか見ません。grant parent やさらに親の設定は見ません。
* 固定ページをルートに作成する場合、サイトの設定を適用します。

公開予約の開始／終了日時のデフォルト設定

---

app/controllers/inquiry/agents/nodes/form_controller.rb
spec/features/inquiry/agents/nodes/form_spec.rb

メールは、Delegator のインスタンスです。Delegator のインスタンスの場合、`try` は、想像通りに動作しません。
Delegator インスタンスの場合、レシーバーオブジェクトの移譲先で `try(:deliver_now)` が評価されます。
このため、メールの移譲先であるメッセージ上で `try(:deliver_now)` が評価されます。
`deliver_now` は、レシーバーオブジェクトが提供するメソッドであり、メッセージオブジェクは `deliver_now` を提供しません。
http://tech.misoca.jp/entry/2015/12/04/110000
※なお Ruby 2.3 から導入された safe navigation operator は想像通りに動作しました。
※想像通りに動作しましたが、修正は Ruby 2.2 でも動作するようにしています。

[fix] unable send inquiry's reply mail

---

app/assets/javascripts/cms/lib/form.coffee.erb
app/controllers/cms/mobile_size_check_controller.rb
app/models/concerns/cms/addon/body.rb
app/models/concerns/ss/addon/mobile_setting.rb
app/views/cms/agents/addons/body/_form.html.erb
app/views/ss/agents/addons/mobile_setting/_form.html.erb
app/views/ss/agents/addons/mobile_setting/_show.html.erb
config/locales/cms/ja.yml
config/locales/ss/ja.yml
config/routes/cms/routes_end.rb
spec/factories/cms/sites.rb
spec/models/cms/page_spec.rb

モバイル設定がenabledの時、htmlのサイズを取得し判定するバリデーションを追加しました。
アップロードされたファイルが本文に挿入されていた場合にはファイルサイズを加えます。

モバイル設定にサイズ（KB）を追加

---

app/controllers/concerns/cms/public_filter.rb

以下はサブディレクトリ対応時のミスではなく、以前からこのコードでした。
~~~
cur_path = @cur_path.dup
~~~

[fix] restore @cur_path.dup

---

README.md
bin/install.sh

インストールスクリプトで投入するサンプルデータに下記を追加しました。
・企業サンプル
・子育て支援サンプル
・オープンデータサンプル
・グループウェア
企業、子育て、オープンデータの各サンプルサイトへのアクセスは、ポート8001～8003でアクセス可能としています。また、対応されていなかった、Recommend機能の有効化、地図をopenlayersに変更、ImageMagickのpolicy.xmlの変更についても対応済みです。
README.mdは従来のパラメータではホスト名がスクリプトに渡らなかったので、"example.jp"の指定の仕方を変えています。また、スクリプト実行の際の環境要件について追記しています。

[modify] install.sh / README.md

---

bin/install.sh

サイト名より”サイト”の文言を削除（デモサイト,Vagrantに合わせる）
”オープンデータサンプルサイト”の場合、英語環境の場合、文字数が40文字を超えるエラーとなるため。

[modify] install.sh

---

app/views/webmail/main/_navi.html.erb

メールを利用するときにbox.depthに0が入っている場合があり、このときnegative argumentのエラーが発生しました。
```
0> box.depth
=> 0
0> "<span class='pad'></span>" * (box.depth - 1)
=> negative argument
```
box.depthが0、もしくは負の値の場合はbox.depthが1の時と同じように空文字列「""」が出力されるように修正しました。

[fix] mail padding

---

app/jobs/application_job.rb
app/models/concerns/ss/model/job_log.rb
app/models/job/task_logger.rb
config/defaults/job.yml
spec/models/job/log_spec.rb
spec/support/ss/database_cleaner_support.rb
spec/support/ss/file.rb

- Fs.mode が :file のとき、ジョブのログをファイルに保存するようにした。
- ジョブの実行後、20% の確率で古い job logs を削除するようにした。
- 何日前のログを削除するかは config/defaults/job.yml の keep_logs に設定する。

job logs 肥大化対応

---

spec/features/gws/monitor/management/trashes_spec.rb

テストでRSpec 実行後に、deprecated 警告が出ていた事象を修正しました。
お手数ですがご確認の程よろしくお願いいたします。

[modify] gws/monitor feature

---

app/models/concerns/cms/addon/sns_poster.rb
app/views/cms/agents/addons/sns_poster/_show.html.erb
config/locales/cms/ja.yml

v2.11 より幾つかの属性を利用するにはドメイン認証が必要になった。
https://developers.facebook.com/docs/graph-api/reference/v2.11/page/feed#custom-image
ただでさえ煩雑な Facebook 投稿連携設定が更に煩雑になる。
よって、プログラムを修正し、ドメイン認証なしでも動作するように修正した。

fb api 2.11

---

app/controllers/concerns/gws/attendance/time_card_filter.rb
app/controllers/gws/attendance/apis/management/users_controller.rb

* [modify] refactor w/ Rubocop: C: Metrics/LineLength: Line is too long.
* [fix] unable to filter out by group in user modal.
* [fix] unable to select proper manageable group if user is `manage_private`

[fix] user select model in gws time card

---

lib/kana/convertor.rb

Updated a broken link reference that was moved from:
http://mecab.googlecode.com/svn/trunk/mecab/doc/format.html
to
https://taku910.github.io/mecab/format.html

Update broken external link

---

Gemfile
Gemfile.lock
Guardfile

- Guard 実行時に、RSpec の実行、Rubocop の実行、Bakeman の実行を停止。ファイルを変更したときだけ実行するようにした。
- Rubocop の監視対象ファイルの拡充。
- 環境変数により RSpec の実行、Rubocop の実行、Bakeman の実行のそれぞれを制御可能に。
- 'terminal-notifier-guard' gem を追加して、Guard の実行結果を Mac の通知センターに通知するように変更。

[modify] refactor Guardfile

---

app/controllers/application_controller.rb
app/controllers/cms/link_check_controller.rb
app/controllers/cms/mobile_size_check_controller.rb
app/controllers/concerns/sns/login_filter.rb
app/controllers/sns/login/environment_controller.rb
app/controllers/sns/login/saml_controller.rb

In some productions, raise "verify_authenticity_token has not been defined" on booting time.
see: https://stackoverflow.com/questions/39260198/verify-authenticity-token-has-not-been-defined

[fix] verify_authenticity_token has not been defined

---

app/models/webmail/imap/base.rb

In my environment, `Errno::EIO` was caused at logging in to imap server

[fix][webmail] rescue imap login error

---

app/jobs/gws/notice/notification_job.rb
app/models/concerns/gws/addon/notice/notification.rb
app/views/gws/agents/addons/notice/notification/_form.html.erb
app/views/gws/agents/addons/notice/notification/_show.html.erb
config/locales/gws/notice/ja.yml
spec/features/gws/notices/notification_spec.rb
spec/jobs/gws/notice/notification_job_spec.rb

these fields are no longer used.
see: #2408

[modify] remove `message_notification` and `email_notification` field

---

app/controllers/application_controller.rb

fix insufficient RFC-5987 interpretation
see: https://tools.ietf.org/html/rfc5987

[fix] download with space separated filename

---

app/models/member/initializer.rb
app/models/member/photo.rb
config/locales/member/ja.yml

メンバー/フォトの承認は、初期リリースの時点（v1.3.0）でエラーになり動作していなかった。

[fix][#2741] remove workflow/approver from member/photo

---

config/environments/development.rb

You can see 'ActiveSupport::Logger' is a default logger class at railties-5.2.3/lib/rails/application/bootstrap.rb:46.
And also you can get several benefits by config.logger is unset.
So you don't need to pass 'ActiveSupport::Logger' explicitly.
And I strongly need long log format for development.

[fixup] app error: undefined method `silence' for Logger in development mode

---

app/models/concerns/gws/addon/portal/portlet/workflow.rb

to protect from causing 500 error on portlet initialized by YAML

[gws][fix][#3299] appropriate default setting to workflow portlet

---

README.md
bin/install.sh

for protecting to install improperly configured ruby (wrong binary).

[fix] add option "--disable-binary" to "rvm install"

---

app/validators/sys/password_validator.rb
config/locales/member/ja.yml

パスワードポリシー 使用禁止文字の表示
「パスワードに使用禁止文字（?%）が含まれています。」の形で括弧内に使用禁止文字を表示させるようにした。

[modified]  パスワードポリシー 使用禁止文字の表示

---

app/views/ezine/agents/addons/body/_form.html.erb
config/defaults/ezine.yml

HTMLエディタを非表示に設定
`config/defaults/ezine.yml` に `html_editor: false`を追記して、値がfalseであればHTMLエディタを非表示に設定

[modified] 【CMS不具合】フォルダー：メールマガジン/会員向けメール配信 HTML エディタを非表示に設定

---

app/views/board/agents/nodes/anpi_post/_anpi_post.html.erb
app/views/member/agents/nodes/my_anpi_post/_form.html.erb
app/views/member/agents/nodes/my_anpi_post/_show.html.erb
app/views/member/agents/nodes/my_profile/index.html.erb

管理側から安否情報の新規作成を行う際に「登録者」を設定していないと、安否掲示板で該当の人を検索すると500エラーになる
K03012-359
`undefined method `name' for nil:NilClass`となっていたので、tryメソッドを使用してmemberがnilであってもエラーが起こらないようにした。

[fix] 【CMS不具合】フォルダー：メンバー/安否 登録者設定無しの場合の500エラーを解消

---

app/models/concerns/gws/addon/portal/portlet/schedule.rb
app/views/gws/agents/addons/portal/portlet/schedule/_form.html.erb
app/views/gws/agents/addons/portal/portlet/schedule/_show.html.erb
config/locales/gws/schedule/ja.yml

it's ambiguous that schedule portlet should show default users or specific users.
so, "schedule_member_mode" is introduced to make this ambiguous feature clearer.

[modify][gws][schedule] add "schedule_member_mode"

---

app/controllers/gws/staff_record/public_duties_controller.rb

K03012-561 IE11でのシラサギの確認
https://web-tips.backlog.jp/view/K03012-561#comment-88210021
エラー原因と考えられる`merge(fix_params)`を削除

[modified] .merge(fix_params)の削除

---

app/assets/javascripts/board/lib/map.js

K03012-359 【CMS不具合】フォルダー：メンバー/安否
「現在地取得」を押すと現在地を取得はできているが、画面が現在地へと移動しないから現在地が取得できているのか分かりづらい。
- setCenterメソッドを追加し、「現在地取得」と同じタイミングで現在地を画面中央に表示させた
- 画面中央に遷移する際に、ズームレベルを初期値に合わして設定した。

【CMS不具合】フォルダー：メンバー/安否　現在地の取得

---

app/models/cms/node.rb

「グループ別ページリスト」非公開化でできない　https://github.com/shirasagi/shirasagi/issues/3809
`Cms::Node::GroupPage`に`include Cms::Addon::Release`を追加。

[fixes] add release addon to pagelist by group #3809

---

app/models/concerns/cms/model/node.rb
app/models/concerns/cms/model/page.rb

携帯プレビューのURLが`https://demo.ss-proj.org/.s1/preview//mobile/docs/page32.html`のように`//mobile`とスラッシュが２つできていたので、スラッシュが１つになるように修正

[fix] able to watch preview for mobile

---

app/assets/javascripts/ss/lib/tree_navi.js
spec/features/workflow/branch_spec.rb

https://web-tips.backlog.jp/view/K03012-678

[fix] remove tree-item class from content-navi-refresh

---

config/environments/development.rb
config/environments/production.rb

| config.assets.js_compressor | size              |
|-----------------------------|-------------------|
| nil                         | 2.2M              |
| :uglifier                   | 1.4M              |
| Uglifier.new(harmony: true) | 1.4M              |
size は次のコマンドで計測: `find public/assets -name '*.js.gz' | xargs du -ch`
ES6 を ES6 のまま uglify できるようになるオプション。
IE11 は ES6 を（直接）実行できないので、「構文エラーです。」や「未定義または NULL 参照のプロパティ `fn' は取得できません。」などというエラーが発生する。

[modify] unset `config.assets.js_compressor`

---

app/assets/stylesheets/gws/schedule/_gws.scss

グループウェアのスケジュールにおいて10分の予定を作成すると、
グループのスケジュールの日表示時に予定の表示領域が狭くなるため文字が見切れてしまう。
最低でも１文字分の横幅を確保した。

[modify]add timeline min-width on calendar

---

.github/workflows/ruby.yml
spec/support/webmail/init.rb

because CRAM-MD5 is deprecated on Ruby 3.1 or later

[Ruby 3.1 準備] use method "PLAIN" to log-in to dovecot

---

Gemfile
Gemfile.lock

because its installation sometimes succeeds, sometimes fails on CI

[modify] remove gem 'ruby-debug-ide'

---

app/models/concerns/cms/content.rb
spec/features/article/agents/parts/page_spec.rb
spec/models/article/page/release_plan_spec.rb

Those aren't accessible in non-preview mode.

[fix][cms] ".and_public" returns "ready" contents in non-preview mode

---

app/assets/javascripts/gws/schedule/lib/calendar.js
app/assets/javascripts/gws/schedule/lib/multiple_calendar.js
app/views/gws/schedule/facilities/index.html.erb

1. 現在日ではない設備の明細を表示。
2. 一覧へ戻るをクリック。
3. クエリパラメータで表示日を指定しているが、効いていないので、現在日が表示される。

[fix][設備予約] クエリパラメータで指定した日時のカレンダーを表示できない問題の修正

---

app/assets/stylesheets/ss/_login.scss

QRコードを読み取りずらいのでQRコードの画像サイズを大きく

[fixup] ワンタイムパスワード（多要素認証の一つとして）

---

package.json
yarn.lock

to fix "The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0."

[modify] bump up sass-loader

---

app/assets/javascripts/map/googlemaps/map.js.erb
app/assets/javascripts/map/openlayers/map.js.erb
public/assets/map/googlemaps/map.js

issue: #5448 
【CMS】記事詳細の地図のスポットアイコンクリック時のポップアップ内HTML構造の変更
以下の表示になるようにHTML構造を変更
- Googleマップ
```html
<div class=" marker marker-info">
<p class="marker-name">マーカー名マーカー名マーカー名マーカー名</p>
<div class="marker-explanation">
<p>説明説明説明説明説明</p>
<p>説明説明説明説明説明説明説明説明説明説明説明説明説明</p>
<p>説明説明説明</p>
</div>
</div>
<p class="marker-link"><a href="https://www.google.co.jp/maps/search/35.400709,135.104301">Googleマップで見る</a></p>
```
- Openlayers
```html
<div class="content marker">
<p class="marker-name">マーカー名マーカー名マーカー名マーカー名</p>
<div class="marker-explanation">
<p>説明説明説明説明説明</p>
<p>説明説明説明説明説明説明説明説明説明説明説明説明説明</p>
<p>説明説明説明</p>
</div>
<p class="marker-link"><a href="https://www.google.co.jp/maps/search/35.400709,135.104301">Googleマップで見る</a></p>
</div>
```
- "marker__link"要素の配置がマップの形式によって異なる
　- Googleマップ："marker …

[fix]issue-5448-map-script

---

app/models/concerns/article/addon/form_export.rb
config/locales/article/ja.yml

issue: #5298
【CMS】記事/定型エクスポートのCSV、jsonの項目追加
記事/定型エクスポート機能において、記事のURLをCSV形式およびJSON形式で出力できるように機能を改善
CSV形式
JSON形式
- 記事URLはデフォルトで表示されるので、出力の要否はサイト管理者が選択不可

[fix] issue 5298

---

.github/workflows/ruby-3.1.yml
.github/workflows/ruby.yml

issue: n/a
captcha 系のテストが失敗するようになったので修正
mini_magick は convert コマンドを実行するが、ubuntu 24.04 から convert コマンドが標準でインストールされなくなった。
明示的にインストールするように修正。

[modify] CI復旧: imagemagick を明示的にインストール

---

app/assets/javascripts/gws/notice/lib/calendar.js
app/assets/javascripts/gws/schedule/lib/calendar.js
app/assets/javascripts/ss/lib/base.js.erb
config/locales/gws/schedule/en.yml
config/locales/gws/schedule/ja.yml
spec/features/ss/js_date_time_format_spec.rb

issue: n/a
スケジュールのカレンダーのヘッダーに、かつて曜日が表示されていた。
ロケールの定義を確認しても曜日が表示されるように設定されている。
にもかかわらず、現在は曜日が表示されない。
曜日が表示されるように修正した。
SS.formatTime / SS.formatDate に不具合があったので、ついでに修正した。

[fix][gws] スケジュールのカレンダーのヘッダーに曜日が表示されない問題の修正

---

config/locales/gws/facility/en.yml
config/locales/gws/facility/ja.yml

issue: #xxxx
GWS > スケジュール > 設備設定 のエクスポート機能
書式編集 = `Translation missing: ja.gws/facility/item.csv.type_datas.cke`エラーの修正
[gws_items_1738633770.csv](https://github.com/user-attachments/files/18702092/gws_items_1738633770.csv)
下記ファイルにロケールを追加
`config/locales/gws/facility/en.yml`
`config/locales/gws/facility/ja.yml`

[fix]gws/facility-items-export-error

---

app/models/concerns/gws/addon/notice/comment_setting.rb
config/defaults/gws.yml
spec/features/gws/notices/comment_state_spec.rb

issue: n/a
グループウェアお知らせの投稿作成時にコメント投稿をデフォルトで有効できるように。
yml に設定を追加。

[modify] gws/notice : default_comment_state

---

app/controllers/gws/memo/notice_user_settings_controller.rb
app/models/gws/initializer.rb
app/views/gws/user_settings/_navi.html.erb
config/locales/gws/en.yml
config/locales/gws/ja.yml
lib/migrations/gws/20250124000000_memo_notice_user_setting_permissions.rb
spec/features/gws/memo/notice_user_settings/basic_spec.rb
spec/lib/migrations/gws/20250124000000_memo_notice_user_setting_permissions_spec.rb

issue: n/a
GWSプロフィールの左ナビにある通知設定を非表示にできるようにする為の修正
権限「プロフィールの通知設定の利用」edit_gws_memo_notice_user_setting を追加
この権限を追加するマイグレーションを作成

[modify] gws/memo_notice : edit_gws_memo_notice_user_setting permission

---

app/controllers/workflow/pages_controller.rb
spec/features/workflow/close_page_spec.rb
spec/features/workflow/edit_requested_page_spec.rb
spec/features/workflow/multi_stage_spec.rb
spec/features/workflow/my_group_spec.rb
spec/features/workflow/release_page_spec.rb

issue: n/a
承認申請時に操作履歴と更新履歴の両方ともが作成されていなかった。
作成されるようにした。

[CMS]  承認申請時の更新履歴と操作履歴の改善

---

app/javascript/controllers/gws/column/radio_controller.js
app/views/gws/agents/columns/radio_button/_column_form.html.erb
spec/features/gws/survey/required_radio_spec.rb

issue: n/a
ラジオボタンを必須にし、さらに「その他」も必須にした場合、そのラジオボタンでその他以外の選択肢に回答しようとすると「その他」への入力を求められる不具合の修正

[fix][gws] 必須の「その他」を持つラジオボタンの動作不良の修正

---

app/assets/javascripts/gws/schedule/lib/calendar.js
app/models/concerns/gws/schedule/calendar_format.rb
spec/features/gws/schedule/plans/attendance_and_comment_spec.rb

スケジュールの欠席表示機能の不具合を修正。
- スケジュールの参加ユーザーは設備管理者１人のみ
- 出欠確認で「不参加」を設定
1. 設備管理者が不参加を選択した場合：
- 欠席表示オフでも予定が表示される
- 欠席表示オンで予定が消える
- 欠席表示オフに戻しても予定が表示されない
2. ブラウザリロードでのみ予定が再表示される状態
- 欠席表示ボタンの状態に応じた表示制御を改善

[fix][gws] calendar

---

app/models/ads/banner.rb
app/models/cms/column/value/url_field2.rb
app/models/concerns/facility/addon/body.rb
app/models/key_visual/image.rb
app/validators/url_validator.rb
spec/features/workflow/save_as_branch_spec.rb
spec/lib/migrations/cms/20220215000000_fix_contains_urls_spec.rb
spec/models/ads/banner_spec.rb
spec/models/cms/column/value/url_field2_spec.rb
spec/models/cms/elasticsearch/page_converter_spec.rb
spec/models/facility/addon/body_spec.rb
spec/models/key_visual/image_spec.rb
spec/validators/url_validator_spec.rb

URLのバリデーション機能を追加し、セキュリティを強化しました。以下のモデルに対してURLバリデーションを実装し、テストケースを追加しました。
1. バリデーションの追加
- 広告バナー（リンクURL）
- `Ads::Banner`モデルの`link_url`に`url: { absolute_path: true }`を追加
- 記事（ブロック入力/リンク）
- `Cms::Column::Value::UrlField2`モデルの`link_url`に`url: { absolute_path: true }`を追加
- 施設情報URL
- `Facility::Addon::Body`モジュールの`related_url`に`url: { absolute_path: true }`を追加
- キービジュアル（リンクURL）
- `KeyVisual::Image`モデルの`link_url`に`url: { absolute_path: true }`を追加
2. テストケースの追加
- `spec/models/facility/addon/body_spec.rb`にバリデーションテストを追加
- 有効なURL（http://, https://, 絶対パス,//www.example.jp/docs/3481.html）のテスト
- 無効なURL（スペースを含むURL, JavaScriptスキーム, フラグメントのみ）のテスト

【CMS】validate url

---

app/views/cms/pages/_change_state.html.erb
spec/features/article/pages/close_permission_spec.rb

一括非公開操作について、公開権限がなくても、一括非公開の操作ができるように修正
下記の権限が付与されたユーザーが一括非公開操作ができるように修正しました。
[“read_private_article_pages”,"read_private_cms_nodes”, “close_private_article_pages”]
- 記事/ページの閲覧（所有）
- 標準機能/フォルダーの閲覧（所有）
- 記事/ページの非公開（所有）
- 記事の編集画面の取り下げ保存については、上記のロールの他、「記事/ページの編集（所有）」が必要です。

[fix] close permission

---

app/jobs/sys/site_export_job.rb
app/jobs/sys/site_import/contents.rb
app/jobs/sys/site_import/file.rb
app/jobs/sys/site_import_job.rb
app/models/fs.rb
lib/ss/filename_utils.rb
spec/jobs/sys/site_import/cms_check_links_ignore_urls_spec.rb
spec/jobs/sys/site_import/guide_spec.rb
spec/jobs/sys/site_import/upload_files_spec.rb

サイトインポートのいくつかの不具合修正
- 記事フォルダーの既定の定型フォームが移行されない問題の修正
- 手続き型ガイドのインポート
- インポート後の画像が別の添付ファイルに差し代わる問題の修正
- リンクチェック除外URLのインポート
- アップローダ配下のunderscoreが連続したファイル名の画像がリンク切れになる問題の修正

[fix] job/sys/site_import_job some issues

---

app/jobs/cms/remove_improper_htmls_job.rb
spec/jobs/cms/remove_improper_htmls/fs_file_spec.rb

不適切なHTML削除タスクの改善
public 配下の fs に htmlファイルがあると検知してしまう件の修正

[modify] cms/remove_improper_htmls : stop remove fs html

---

app/views/sns/login/redirect.html.erb
config/locales/ss/en.yml
config/locales/ss/ja.yml

リダイレクト警告画面の「送信」ボタンを「外部サイトへ進む」へ変更

[modify] rename send button

---

app/controllers/concerns/cms/syntax_checkable.rb
app/models/concerns/workflow/approver.rb
app/views/workflow/agents/addons/approver/_show.html.erb
config/locales/workflow/en.yml
config/locales/workflow/ja.yml
spec/features/workflow/edit_requested_page_spec.rb

アクセシビリティエラーのある記事の「公開」「差し替え」承認の制限
- アクセシビリティチェックを無視して保存する権限がないユーザーが、アクセシビリティエラーがある記事の「公開」を承認できないように修正
- アクセシビリティチェックを無視して保存する権限がないユーザーが、アクセシビリティエラーがある記事の「差し替え」を承認できないように修正
- アクセシビリティチェックを無視して保存する権限があるユーザーが、アクセシビリティエラーのある記事を「公開」または「差し替え」しようとした場合にアクセシビリティエラーの表示がされる
下記の項目にアクセシビリティエラーがある記事は今回の修正の制限の対象外になります。
- ブロック入力「見出し」（hタグ順序エラー）
- ブロック入力「リンク」（リンクテキスト未入力）
- ブロック入力「添付ファイル」（リンクテキスト未入力）

[fix][cms]approval-disable-without-permission

---

app/jobs/gws/workflow2/route_migration_job.rb
config/locales/gws/workflow2/en.yml
config/locales/gws/workflow2/ja.yml
lib/tasks/gws/workflow2.rake
lib/tasks/gws/workflow2.rb
spec/jobs/gws/workflow2/route_migration_job_spec.rb
spec/lib/tasks/gws/workflow2/migrate_route_spec.rb

- Gws::Workflow::Route を Gws::Workflow2::Route へ移行するタスクとジョブ。
- 元となる Gws::Workflow::Route は削除されずに残る（これはCMSと共有されている可能性があるため）。
- 移行時、Gws::Workflow2::Route の備考に移行したことを示す証跡を残す。

[gws][workflow2] 承認ルートの移行タスクとジョブ

---

app/models/concerns/ss/model/role.rb
config/environments/development.rb
config/environments/test.rb

1. development 環境では Rails のバージョンアップにより rake で routes が読み込まれなくなった。 ( おそらく高速化した )
2. routes 内の initializer が読み込まれなくなった。
3. SS::Model::Role の permission_names が想定通りに初期化されず空になる。
4. permission_names を参照する rake タスクが正常に動作しない。
permission_names の参照時に routes を読み込みように変更。
routes を読み込む処理はそれほど重くないが、 initializer のみを読み込みできるとより良い。

[fix] ss model role permission_names

---

config/puma.rb

- GWS のメニュー全クリック＋CMS記事ページ一覧で worker killer が発動しない程度にメモリを増加
- 1分ごとに "PumaWorkerKiller: Consuming 2024.40625 mb with master and 2 workers" とログに出力されてウザいので `reaper_status_logs` を false に

ワーカーのメモリー使用量の制限値の調整

---

app/models/concerns/cms/addon/node_twitter_post_setting.rb
app/models/concerns/cms/addon/twitter_poster.rb
app/views/cms/agents/addons/node_twitter_post_setting/_form.html.erb
app/views/cms/agents/addons/node_twitter_post_setting/_show.html.erb
app/views/cms/agents/addons/twitter_poster/_form.html.erb
app/views/cms/agents/addons/twitter_poster/_show.html.erb
app/views/ss/agents/addons/twitter_setting/_show.html.erb
config/locales/cms/ja.yml
config/locales/sns_poster/ja.yml
config/locales/ss/en.yml
config/locales/ss/ja.yml
spec/features/cms/sns_post/logs/basic_spec.rb
spec/features/cms/sns_post/twitter/approval_spec.rb
spec/features/cms/sns_post/twitter/basic_spec.rb
spec/features/cms/sns_post/twitter/merge_spec.rb
spec/features/cms/sns_post/twitter/release_page_spec.rb
spec/features/cms/sns_post/twitter/unpostable_spec.rb
spec/models/history/trash/restore_article_page_spec.rb
spec/models/history/trash/restore_cms_page_spec.rb

CMSのTwitter連携の表記をX(旧Twitter)連携に変更
記事ページのTwitter連携設定の twitter_post_format が使用されなくなった為、削除

[modify] rename label of twitter to x

---

app/views/inquiry/agents/addons/input_setting/_form.html.erb

ダイアログのオープンとクローズを何回か繰り返した後、キーワードの追加ボタンをクリックすると、ダイアログを開いた数分だけのキーワードが一気に追加される問題の修正
document にイベントハンドラーを登録しているが、ダイアログを閉じてもdocumentのイベントハンドラーは残ったままとなる。
ダイアログを開くたびにdocumentのイベントハンドラーが増えていく。このため、キーワードの追加ボタンをクリックすると、キーワードが一気に追加される。
document にイベントハンドラーを登録するのではなく、アドオン要素にイベントハンドラーを登録するようにした。
ダイアログを閉じるとアドオン要素は削除される。削除される際にイベントハンドラーも削除される。
キーワードの追加をクリックしても一つしか追加されない。

[cms][inquiry] キーワードが一気に追加される問題の修正

---

app/assets/stylesheets/ss/link_item/_ss.scss
app/views/sys/ads/_form_link_items.html.erb
spec/features/sys/ad_spec.rb

ログイン広告をすべて削除すると、削除できない問題の修正。
空のレコードを一つ残しておくと削除は可能だった。

[fix] unable to delete ad

---

app/helpers/gws/layout_helper.rb
app/views/gws/agents/addons/system/menu_setting/_form.html.erb
app/views/gws/agents/addons/system/menu_setting/_show.html.erb

グループウェアのメニューアイコンのスタイル調整
- `<input>` の表示崩れ修正。
- アイコンを表す `<span>` に `role="img"` と `aria-hidden="true"` を付与。
https://waic.jp/translations/WCAG21/Techniques/aria/ARIA24
- _form.html.erb でも `aria-hidden="true"` を付与したが、`aria-label="アイコンの説明文字列"` を付与した方が良いかも。

[fixup] gws change menu icon (#5704)

---

app/jobs/concerns/ss/copy/cms_columns.rb
app/jobs/concerns/ss/copy/cms_contents.rb
app/jobs/concerns/ss/copy/cms_forms.rb
app/jobs/concerns/ss/copy/cms_layouts.rb
app/jobs/concerns/ss/copy/cms_nodes.rb
app/jobs/concerns/ss/copy/cms_pages.rb
app/jobs/concerns/ss/copy/cms_parts.rb
app/jobs/concerns/ss/copy/ss_files.rb

サイト複製時に以下のエラーがログに記録されていた。
~~~
E, [2025-07-29T11:00:46.894177 #42719] ERROR -- : [ActiveJob] [Sys::SiteCopyJob] [3d8718e9-d797-4cd5-ad67-a7ef6f1775c1] NoMethodError (undefined method `related_page_ids' for #<Ads::Banner _id: 234, created: 2025-07-29 02:00:46.591996357 UTC, updated: 2025-07-29 02:00:46.786423392 UTC, deleted: nil, text_index: nil, user_id: 1, site_id: 6, group_ids: [1], state: "public", name: "市政情報", index_name: nil, filename: "ad/page35.html", depth: 2, order: 60, released: 2025-06-02 08:58:07.113 UTC, released_type: "fixed", first_released: 2025-06-02 08:58:07.113 UTC, imported: nil, md5: nil, redirect_link: nil, layout_id: nil, body_layout_id: nil, expiration_setting_type: "site", route: "ads/banner", size: 2449, category_ids: [], ads_category_ids: [789], release_date: …

[fix] site copy errors

---

app/models/gws/tabular.rb
app/models/gws/tabular/column/lookup_field.rb
app/models/gws/tabular/file.rb
app/models/gws/tabular/file/generator.rb
app/models/gws/tabular/file/notification_subject_service.rb
app/models/gws/tabular/form/delete_service.rb
app/models/gws/tabular/form_migration.rb
app/models/gws/tabular/initializer.rb
app/models/ss.rb
config/application.rb
spec/jobs/gws/tabular/form_trash_purge_job_spec.rb

Gws::Tabular::FileXXXXX のロード方法が不味くて、汎用DBにアップロードしたファイルを閲覧できない問題の修正。
Gws::Tabular::FileXXXXX のロード方法を一度修正したが、とある環境で `Mongo::Error::OperationFailure ([225:TransactionTooOld]: Retryable write with txnNumber 368 is prohibited on session ` という謎のエラーに遭遇。
そこで、Gws::Tabular::FileXXXXX のロード方法を抜本的に見直し。

[fixup^8][gws] 汎用DB (#5672)

---

app/assets/javascripts/cms/preview/main.js.erb
app/assets/javascripts/ss/lib/search_ui.js
app/views/cms/apis/preview/workflow/wizard/approver_setting.html.erb
app/views/cms/apis/preview/workflow/wizard/approver_setting_multi.html.erb
app/views/cms/apis/preview/workflow/wizard/approver_setting_restart.html.erb
app/views/cms/preview/_tool.html.erb
app/views/cms/preview/_tool_left.html.erb
spec/features/article/pages/preview_editing/apply_approval_spec.rb
spec/features/article/pages/preview_editing/basic_body_spec.rb

Rails 8.0 へ更新時に jQuery UI の廃止された機能やプロパティが既定で利用できなくなった。
このためプレビューでの承認が動作しなくなったのが主たる原因。
プレビューでの承認では、他に問題があったが修正した。

[fix][cms] プレビューで承認できない問題の修正

---

app/views/ss/tasks/_box.html.erb
spec/features/cms/nodes_download_spec.rb

CMSの一括インポートのtask logがダウンロードできない問題の修正

[fix] tasks log_sequence

---

app/controllers/concerns/gws/schedule/calendar_filter.rb
app/views/gws/schedule/plans/index.html.erb

2025年8月1日になったら `spec/features/gws/workload/works/set_due_end_on_spec.rb:414` が失敗するようになった。
その修正。
Timecop で現在日が変更されていることを考慮して、未指定とはせずに明示的に指定するようにした。

[fix][workload] spec failures

---

app/controllers/cms/agents/parts/crumb_controller.rb
spec/features/cms/agents/parts/crumb_spec.rb

記事ページのパンくずの表示修正
- 参照オブジェクトを修正
- テストケース追加

[fix]docs-breadcrumb
