shirasagi/shirasagi

Gemfile, Gemfile.lock
デバッグをしやすくするために、開発環境とテスト環境にpry関係のGemを追加してみました。
=> Use 4 pry-* gems for development

app/models/concerns/ss/file/model.rb, app/models/fs/initializer.rb, app/models/ss/config.rb, config/locales/ja.yml, config/samples/cms.yml, config/samples/environment.yml
添付ファイル容量制限：https://github.com/shirasagi/shirasagi/issues/102
=> add config Tempfilesize

app/helpers/cms/node_helper.rb, app/models/cms/addon.rb, app/models/concerns/cms/node/model.rb, app/views/cms/agents/addons/node_setting/_form.html.erb, app/views/cms/agents/addons/node_setting/_show.html.erb, app/views/cms/nodes/_form.html.erb, app/views/cms/nodes/_show.html.erb, config/locales/cms/ja.yml
デフォルトの表示画面（フォルダー「カテゴリー/ページリスト」）:https://github.com/shirasagi/shirasagi/issues/94
=> add default module setting

app/controllers/concerns/cms/public_filter/layout.rb
=> add template #{part_name}, #{parent_name}

app/models/concerns/ss/task/model.rb
SS::Task::Model should not depend on Cms::Task.
=> Fix SS::Task::Model module's ready class method

app/controllers/article/agents/parts/page_controller.rb, app/controllers/cms/agents/parts/page_controller.rb, app/models/cms/addon/list.rb
=> add template #{request_dir} to conditions

app/controllers/kana/dictionaries_controller.rb, app/models/kana/dictionary.rb, app/views/kana/dictionaries/index.html.erb, spec/features/kana/dictionaries_spec.rb, spec/spec_helper.rb
かな辞書モジュールです。
テストを実行し、テストが成功することを確認しています。
=> add: kana dictionary module. aka mecab user dictionary module.

.travis.d/before_script.d/10-copy-config.sh, .travis.d/before_script.sh, .travis.d/install.d/10-imagemagick.sh, .travis.d/install.d/20-mecab.sh, .travis.d/install.d/90-bundle-install.sh, .travis.d/install.sh, .travis.yml
Travis CI で MeCab を利用したテストができるかどうかを実験する。
=> [WIP PR] study to run mecab test in travis ci.

app/views/ezine/agents/nodes/form/new.html.erb, app/views/ezine/agents/nodes/form/remove.html.erb, app/views/ezine/agents/nodes/form/update.html.erb, app/views/ezine/agents/nodes/page/index.html.erb, app/views/ezine/pages/index.html.erb, app/views/ezine/test_members/index.html.erb
#131 の以下の不具合に対応しましたのでご確認をお願いします。
> ■公開画面
> ・一覧画面
> 　日付は「○年○月○日」にしてください。
> 　「Ezine.more」は消してください。
> 　配信していない記事も出ますが問題ないでしょうか。
> 
> ・配信登録画面
> &lt;div class="ezine-html"&gt; 配信登録 &lt;/div&gt;
> を
> &lt;h2 class="ezine-html"&gt; 配信登録 &lt;/h2&gt;
> に変更してください。
> 
> ■管理画面
> 一覧部分で記事タイトルやメールアドレス等がリンクになっていません。
=> Fix ezine module

.travis.d/install.d/30-open-jtalk.sh, .travis.yml
Travis CI で Open JTalk を使用したテストを有効にする。
F/S しながら、Open JTalk を有効にしていく。
=> [WIP PR] study to enable open jtalk test on travis ci.

app/assets/javascripts/ss/ss.coffee.erb
ファイルアップロード画面でページネーションを行うとデザインが崩れる#122
=> fix: modal paginate

app/models/job/master_service.rb, app/models/job/service.rb, app/models/job/worker.rb, app/models/voice/voice_file.rb, lib/voice/open_jtalk.rb, lib/voice/wav_to_mp3.rb
音声合成時に発生したエラーが、正しく記録されない障害を修正しました。
=> closes #139: fix voice synthesis error collecting issue.

app/controllers/ezine/pages_controller.rb, app/models/ezine/page.rb
Include PageFilter.
PageFilter needs us to include ReleasePlan addon.
PageFilter also includes CrudFilter, so remove it.
=> Make an ezine page inherit the parent layout (#153)

app/mailers/ezine/mailer.rb, app/models/ezine/config.rb, config/samples/ezine.yml
=> Fix e-mail sender address

app/controllers/ezine/agents/nodes/backnumber_controller.rb, app/controllers/ezine/agents/nodes/page_controller.rb, app/models/ezine/initializer.rb, app/models/ezine/node.rb, app/views/ezine/agents/nodes/backnumber/index.html.erb, app/views/ezine/agents/nodes/page/index.html.erb, config/locales/ezine/ja.yml, config/routes/ezine/routes.rb
For #131 
Reference: https://github.com/shirasagi/shirasagi/issues/131#issuecomment-72005442
=> [WIP PR] Fix ezine module routing

app/views/ezine/mailer/verification_mail.ja.text.erb
Refer #128 comment https://github.com/shirasagi/shirasagi/issues/128#issuecomment-71291216
=> Add [ ] to verifcation mail subject

app/controllers/ezine/agents/nodes/form_controller.rb, app/views/ezine/agents/nodes/form/add.html.erb, app/views/ezine/agents/nodes/form/delete.html.erb, app/views/ezine/agents/nodes/form/update.html.erb
Don't use `request.env['HTTP_REFERER']`.
=> Refactor ezine module

app/views/ezine/mailer/verification_mail.ja.text.erb
Fix from `/verification` to `/verify`.
=> Fix verification_mail URL

app/controllers/inquiry/answers_controller.rb, app/models/inquiry/node.rb, app/views/inquiry/answers/_menu.html.erb, app/views/inquiry/columns/index.html.erb, config/routes/inquiry/routes.rb
=> download inquiry answers

app/controllers/cms/preview_controller.rb, app/controllers/cms/public_controller.rb, app/controllers/concerns/mobile/public_filter.rb
=> fix: mobile preview

app/mailers/ezine/mailer.rb, app/models/ezine/addon.rb, app/models/ezine/config.rb, app/models/ezine/node.rb, app/views/ezine/agents/addons/reply/_form.html.erb, app/views/ezine/agents/addons/reply/_show.html.erb, app/views/ezine/agents/addons/sender_address/_form.html.erb, app/views/ezine/agents/addons/sender_address/_show.html.erb, app/views/ezine/agents/addons/signature/_form.html.erb, app/views/ezine/agents/addons/signature/_show.html.erb, app/views/ezine/mailer/page_mail.ja.html.erb, app/views/ezine/mailer/page_mail.ja.text.erb, app/views/ezine/mailer/verification_mail.ja.text.erb, config/locales/ezine/ja.yml, config/samples/ezine.yml
Implement 3 addons for signature, sender name and email address, and upper and lower text for verification mail.
=> Fix ezine addon

app/models/ezine/addon.rb, app/views/ezine/agents/addons/reply/_form.html.erb, app/views/ezine/agents/addons/reply/_show.html.erb, app/views/ezine/mailer/verification_mail.ja.text.erb, config/locales/ezine/ja.yml
Add `signature` field to reply addon (`Ezine::Addon::Reply`).
**This is WIP Pull Request, so DO NOT merge yet now.**
=> Add signature to reply addon

app/controllers/ezine/pages_controller.rb, app/models/ezine/page.rb
Test delivery is correct now?
**Do NOT merge yet because this is WIP PR.**
=> [WIP] Fix test members selection

app/controllers/cms/groups_controller.rb, app/controllers/cms/users_controller.rb, app/controllers/cms/workflow/routes_controller.rb, app/controllers/concerns/cms/searchable_crud_filter.rb, app/models/concerns/workflow/extensions/route.rb, app/models/concerns/workflow/route/model.rb, app/models/workflow/addon.rb, spec/features/cms/workflow/search_approvers_spec.rb, spec/models/cms/workflow/route_spec.rb, spec/models/workflow/addon/approver_spec.rb
* refactor with rubcop.
* refactor with codeclimate.
=> fix workflow code climate

app/models/concerns/voice/downloadable.rb, app/models/job/service.rb, app/models/voice/voice_file.rb
refince rescue and backtrace log when voice file is creating.
=> refince rescue and backtrace log.

app/controllers/cms/generate_nodes_controller.rb, app/controllers/cms/generate_pages_controller.rb, app/controllers/cms/node/generate_nodes_controller.rb, app/controllers/cms/node/generate_pages_controller.rb, app/controllers/concerns/ss/exec_filter.rb, app/controllers/ezine/pages_controller.rb, app/controllers/voice/main_controller.rb, lib/ss/rake_runner.rb, lib/voice/command.rb, lib/voice/open_jtalk.rb, lib/voice/wav_to_mp3.rb, spec/features/cms/workflow/routes_spec.rb
=> #197: close unnecessary stdin, stdout and stderr when external command is going to execute

app/controllers/cms/workflow/search_approvers_controller.rb, app/models/concerns/ss/user/model.rb, app/models/concerns/workflow/route/model.rb, app/views/cms/workflow/routes/_form.html.erb, app/views/cms/workflow/routes/_show.html.erb, app/views/cms/workflow/search_approvers/index.html.erb, app/views/workflow/agents/addons/approver/_show.html.erb, app/views/workflow/wizard/approver_setting.html.erb, app/views/workflow/wizard/approver_setting_multi.html.erb
=> [#204] fix workflow issue.

spec/features/cms/workflow/search_approvers_spec.rb
fix `spec/features/cms/workflow/search_approvers_spec.rb` failure.
=> fix test failure.

app/controllers/kana/dictionaries_controller.rb, app/models/kana/dictionary.rb, app/views/kana/dictionaries/_menu.html.erb, app/views/kana/dictionaries/build_confirmation.html.erb, config/locales/kana/ja.yml, config/locales/ss/ja.yml, config/routes/kana/routes.rb, spec/features/kana/dictionaries_spec.rb, spec/models/kana/dictionary_spec.rb
=> [#206] add confirmation before building dictionary

lib/voice/scraper.rb, spec/lib/voice/scraper_spec.rb
=> fix javascript voice synthesis issue.

spec/fixtures/voice/test-002.html, spec/lib/voice/scraper_spec.rb
there is a rubocop issues on `spec/lib/voice/scraper_spec.rb`.
this pr is fix it.
=> fix voice scraper_spec rubocop issue.

app/views/kana/dictionaries/_show.html.erb
=> [#218] change readonly box instead of textarea.

app/controllers/ezine/pages_controller.rb
Reject the members that `state` is `false` in `app/views/ezine/pages/_deliver_form.html.erb`.
=> Fix @members_email with state column

app/mailers/application_mailer.rb
Set default values of `config/samples/mail.yml` to keep current behavior.
=> Fix mail configuration

app/controllers/ezine/pages_controller.rb, app/models/ezine/member.rb, app/models/ezine/test_member.rb, app/views/ezine/members/_form.html.erb, app/views/ezine/members/_show.html.erb, app/views/ezine/members/index.html.erb, config/locales/ezine/ja.yml
Replace `Ezine::Member.where(state: true)` with `scope` named `enabled`.
Refactoring of `Ezine::Member`'s `state` field.
* `Boolean` -> `String`
* `true` -> `'enabled'`
* `false` -> `'disabled'`
=> Refactor member state

lib/ss/rake_runner.rb
Thanks @gouf 
https://github.com/gouf/shirasagi/commit/03c0d193cf3d1e1d31ddd06a13207931928e0b94#commitcomment-9970367
=> fix command line injection vulnerability.

app/views/cms/search_categories/index.html.erb, app/views/cms/search_groups/index.html.erb
add pagenation to 
- cms/search_groups/index.html.erb
- cms/search_categories/index.html.erb.
see #246
=> add pagenation

app/controllers/concerns/mobile/public_filter.rb
=> fix: mobile fs link #192

app/controllers/facility/agents/nodes/page_controller.rb, app/controllers/facility/agents/nodes/search_controller.rb, app/controllers/facility/images_controller.rb, app/controllers/facility/maps_controller.rb, app/controllers/facility/pages_controller.rb, app/views/workflow/agents/addons/approver/_show.html.erb
施設地図・施設写真ページで承認申請できない #251 
地図・写真ページの権限は固定ページと同じ状態
=> fix facility page approve

Gemfile, Gemfile.lock, spec/factories/cms/layouts.rb, spec/factories/cms/member.rb, spec/factories/cms/pages.rb, spec/factories/cms/parts.rb, spec/factories/cms/roles.rb, spec/factories/cms/users.rb, spec/factories/history/logs.rb, spec/factories/ss/groups.rb, spec/factories/ss/sites.rb, spec/factories/ss/users.rb, spec/factories/sys/roles.rb, spec/factories/sys/sites.rb, spec/features/cms/node/parts_spec.rb, spec/lib/ss/debug_spec.rb, spec/models/job/model_spec.rb, spec/models/sys/site_spec.rb, spec/models/voice/synthesis_job_spec.rb, spec/spec_helper.rb, spec/support/cms/user.rb, spec/support/ss/mongoid.rb, spec/support/ss/user.rb, spec/support/sys/user.rb
=> add database cleaner.

config/initializers/multipart_part_limit.rb
=> add configuration initializer for rack multiparts option #254

spec/spec_helper.rb, spec/support/ss/mongoid.rb
* extend RSpec by standard way instead of rewriting RSpec internal method.
* add :dbscope option and its default value.
=> [#113] enhancement.

lib/voice/scraper.rb, spec/fixtures/voice/test-003.html, spec/lib/voice/scraper_spec.rb
=> [#264, #266] fix issue.

spec/support/ss/mongoid.rb
* fix mongoid.rb rubocop issue.
* remove unnecessary if statement.
=> fix mongoid.rb rubocop issue.

app/controllers/cms/node/generate_nodes_controller.rb, app/controllers/cms/node/generate_pages_controller.rb, spec/features/cms/node/generate_nodes_spec.rb
* fix issue.
* fix same issue on generate pages.
* add specs.
see #272.
=> [#272] fix issue.

app/controllers/concerns/cms/page_filter.rb, app/controllers/workflow/pages_controller.rb, app/helpers/cms/form_helper.rb, app/models/article/page.rb, app/models/cms/addon/file.rb, app/models/cms/page.rb, app/models/concerns/cms/page/model.rb, app/models/event/page.rb, app/models/facility/addon.rb, app/models/faq/page.rb, app/models/workflow/addon/branch.rb, app/views/cms/agents/addons/release_plan/_form.html.erb, app/views/cms/crud/_link_check.html.erb, app/views/cms/crud/_menu.html.erb, app/views/cms/crud/copy.html.erb, app/views/facility/images/_menu.html.erb, app/views/facility/maps/_menu.html.erb, app/views/workflow/agents/addons/approver/_show.html.erb, app/views/workflow/agents/addons/branch/_show.html.erb, app/views/workflow/pages/branch.html.erb, config/locales/cms/ja.yml, config/locales/ss/ja.yml, config/locales/workflow/ja.yml, config/routes/article/routes.rb, config/routes/cms/routes_end.rb, config/routes/event/routes.rb, config/routes/facility/routes.rb, config/routes/faq/routes.rb, config/routes/workflow/routes.rb
=> page clone and create branch

config/routes/workflow/routes.rb
=> fix: workflow routing

app/views/job/cms/logs/_show.html.erb
* remove text_area_tag.
* set overflow style to scroll.
=> [#288] remove text-area and adjust style.

app/controllers/sns/login_controller.rb, app/models/concerns/ss/user/model.rb, app/views/sns/login/login.html.erb, spec/factories/cms/users.rb, spec/features/sns/login_spec.rb, spec/support/cms/user.rb, spec/support/ss/user.rb
=> change login parameter: in_id --> email.

app/views/cms/crud/copy.html.erb, app/views/cms/crud/move.html.erb, app/views/history/cms/backups/restore.html.erb, app/views/history/cms/logs/delete.html.erb, app/views/history/cms/logs/download.html.erb, app/views/job/cms/logs/batch_destroy.html.erb, app/views/job/cms/logs/download.html.erb, app/views/kana/dictionaries/build_confirmation.html.erb, app/views/ldap/import/import_confirmation.html.erb, app/views/ldap/import/sync_confirmation.html.erb, app/views/ss/crud/delete.html.erb, app/views/ss/crud/edit.html.erb, app/views/ss/crud/new.html.erb, app/views/uploader/files/delete.html.erb, app/views/uploader/files/edit.html.erb, app/views/uploader/files/new_directory.erb, app/views/uploader/files/new_files.erb
=> fix: cancel button type for ie8

app/models/cms/addon/file.rb
=> add allowed_other_user_files? method & refactor

app/controllers/faq/agents/nodes/search_controller.rb, app/controllers/faq/agents/parts/search_controller.rb, app/views/faq/agents/nodes/search/index.html.erb, app/views/faq/agents/parts/search/index.erb
=> fix faq search form mobile path

app/controllers/workflow/pages_controller.rb
#284 で追加した処理にてfile addonをincludeしていない場合の対応
=> fix: workflow #284

app/models/job/log.rb, app/models/job/service.rb, spec/factories/job/logs.rb, spec/factories/job/models.rb, spec/features/job/cms/logs_spec.rb, spec/models/job/log_spec.rb
=> [#296] fix job log download issue and add some specs.

app/controllers/facility/agents/tasks/node/pages_controller.rb, app/models/facility/image.rb, app/models/facility/map.rb
=> stop generate facility pages

app/views/job/cms/logs/_show.html.erb
=> [#288] back to use textarea and set "readonly: true" and height style.

app/controllers/cms/preview_controller.rb, app/controllers/concerns/fs/file_filter.rb, app/controllers/fs/files_controller.rb
=> fix: preview thumb image

app/models/ezine/page.rb, app/models/ezine/result.rb, app/models/ezine/task.rb, app/views/ezine/pages/index.html.erb
#229 の解消策として，`demongoize` を使うのでもとりあえずハッシュにするのでもなく，`embeds_many` を使うようにした．
=> Implement Ezine::Result as embeds_many of Ezine::Page

app/controllers/concerns/cms/page_filter.rb
=> add space to cloned page name

app/controllers/workflow/routes_controller.rb, app/controllers/workflow/wizard_controller.rb, app/models/workflow/route.rb, app/views/workflow/agents/addons/approver/_show.html.erb, app/views/workflow/wizard/approver_setting.html.erb
=> fix undefined method `cur_site=`.

Gemfile, Gemfile.lock, app/views/workflow/routes/_form.html.erb, spec/features/workflow/routes_spec.rb, spec/spec_helper.rb, spec/support/ss/color_box_support.rb, spec/support/ss/database_cleaner_support.rb, spec/support/ss/mongoid.rb
workflow module javascript test.
=> workflow js test

.gitignore, config/environments/development.rb
* revert development log level to warn
* add "/config/environments" to .gitignore protecting from accidental commit.
=> development log level

app/views/ldap/server/entity.html.erb, app/views/ldap/server/index.html.erb, config/locales/ldap/ja.yml, lib/ldap/connection.rb
* refactor ldap locales
* fix undefined method issue
=> refactor ldap locales

spec/features/article/pages_spec.rb, spec/features/cms/pages_spec.rb, spec/features/event/pages_spec.rb, spec/features/faq/pages_spec.rb
=> add spec for move & clone page

app/models/job/service.rb, app/models/job/task.rb, app/models/job/worker.rb, spec/factories/job/task.rb, spec/models/job/task_spec.rb, spec/models/job/worker_spec.rb, spec/models/voice/synthesis_job_spec.rb
* rename "Job::Model" to "Job::Task"
=> refactor job model

app/controllers/cms/agents/tasks/pages_controller.rb, app/controllers/concerns/cms/page_filter.rb, app/controllers/workflow/pages_controller.rb, app/models/workflow/addon/branch.rb, app/views/cms/agents/addons/release_plan/_form.html.erb
=> add release plan to brach page #333

app/models/uploader/file.rb
アップローダー　.coffee アップロード時にエラー #268
=> fix: uploader #268

app/models/cms/addon/file.rb, app/views/cms/crud/move.html.erb, config/locales/cms/ja.yml
=> fix: move action #250

app/models/workflow/addon/branch.rb, app/views/workflow/agents/addons/branch/_show.html.erb, app/views/workflow/pages/branch.html.erb, config/locales/workflow/ja.yml
* #359 を修正
* ブランチページの静的書き出しを無効に
=> fix #359 & disable static file of branch page

app/controllers/concerns/mobile/public_filter.rb, lib/mobile/converter.rb, spec/lib/mobile/converter_spec.rb
=> [#293] fix mobile tag conversion issue.

app/models/concerns/cms/member/model.rb, spec/models/cms/member_spec.rb
this issue is identified by od-96.
=> fix empty email issue on cms_members.

app/controllers/concerns/cms/public_filter/layout.rb
=> disable ajax_view in preview for #387 #385

app/models/fs/uploaded_file.rb, db/seeds/demo/load.rb, spec/features/fs/files_spec.rb
create Fs::UploadedFile#create_from_file method and reduce duplicated code
=> reduce duplicated code

app/controllers/voice/main_controller.rb, app/models/voice/synthesis_job.rb, spec/models/voice/synthesis_job_spec.rb
* add `Voice::SynthesisJob.purge_pending_tasks` method to purge pending tasks.
* add `before_action :purge_pending_tasks` to Voice::MainController.
* stabilize specs.
=> [#388] implement purge logic to model and call it from controller with some probability

app/controllers/inquiry/nodes_controller.rb, app/views/inquiry/agents/nodes/form/results.html.erb, app/views/inquiry/agents/nodes/node/index.html.erb, config/locales/inquiry/ja.yml
=> fix html #403

app/models/concerns/ss/document.rb, spec/models/ss/document_spec.rb
アドバイスに従って先日の #418 の変更を更に微調整
Thx to @sunny4381 :+1:
=> Tweak fix timestamp initialization

app/models/sitemap/addon.rb
=> add sort to load_sitemap_urls #374

app/assets/javascripts/ss/lib/list_ui.coffee.erb, app/views/uploader/files/_menu.html.erb, app/views/uploader/files/index.html.erb
=> fix uploader #389

app/controllers/concerns/facility/page_filter.rb, app/models/facility/import_job.rb
施設情報インポート(#179) のリファクタ
関連：https://github.com/shirasagi/shirasagi/commit/804b7df63f0753b22aeb219473e8b13c0400e92c
=> fix for rubocop #179

app/models/cms/reference.rb, spec/models/cms/user_spec.rb
=> fix issue.

app/controllers/facility/agents/nodes/search_controller.rb, app/views/facility/agents/addons/search_result/view/_tabs.html.erb
=> facility: fix search with keyword

app/models/sitemap/addon.rb
=> sitemap: fix sort in load_sitemap_urls #374

lib/migrations/ss/20150518040533_fix_ss_users_indexes.rb
* add `sparse` to email index.
* add `uid` index.
=> add SS::User index migration.

app/models/concerns/cms/node/model.rb, app/models/concerns/cms/page/model.rb, spec/features/cms/move_spec.rb
=> fix folder and page move #457

spec/features/workflow/branch_spec.rb
=> add branch spec

app/controllers/cms/editor_templates_controller.rb, app/helpers/editor_helper.rb, app/models/cms/addon.rb, app/models/cms/config.rb, app/models/cms/editor_template.rb, app/views/cms/agents/addons/thumb/_form.html.erb, app/views/cms/agents/addons/thumb/_show.html.erb, app/views/cms/editor_templates/_ckeditor_template.js.erb, app/views/cms/editor_templates/_form.html.erb, app/views/cms/editor_templates/_show.html.erb, app/views/cms/editor_templates/_tinymce_template.json.jbuilder, app/views/cms/editor_templates/template.js.erb, app/views/cms/editor_templates/template.json.jbuilder, app/views/cms/main/_navi.html.erb, config/locales/cms/ja.yml, config/routes/cms/routes_end.rb, config/samples/cms.yml, spec/factories/cms/editor_templates.rb, spec/features/cms/editor_templates_spec.rb, spec/models/cms/editor_template_spec.rb
* add Cms::EditorTemplate model
* add Cms::EditorTemplatesController and its view
* add its routes
* add its specs
see #439
=> [#439] add editor template functionality

config/locales/contact/ja.yml
add `contact/addon/page` locale
=> backport from od

app/models/concerns/ss/user/model.rb, lib/migrations/ss/20150518040533_fix_ss_users_indexes.rb
=> fix ss migartion issue

app/models/concerns/ss/file/model.rb, app/views/sns/user/temp_files/index.html.erb, config/locales/ss/ja.yml
=> resize image when upload

app/models/cms/config.rb, app/views/facility/agents/nodes/page/index.html.erb, app/views/map/agents/addons/page/_form.html.erb, config/samples/cms.yml
=> map: add config number of markers #463

app/models/concerns/ss/file/model.rb, config/locales/ja.yml, spec/models/ss/file_spec.rb
=> improve error message on exceeding file size limitation

config/routes/cms/routes_end.rb, config/routes/facility/routes.rb, config/routes/sys/routes.rb
=> search apis: fix search in modal

app/models/ss/config.rb, app/models/ss/initializer.rb, config/application.rb
=> [#478] fix `rake unicorn:start` command failure

.travis.yml
see:
* http://stackoverflow.com/questions/26299552/travis-sudo-is-disabled
* https://github.com/travis-ci/travis-build/blob/master/.travis.yml
=> add `sudo: true` to .travis.yml

Gemfile.lock, README.md
ref.
https://github.com/shirasagi/shirasagi/issues/489
https://github.com/bundler/bundler/issues/3697
=> Upgrade Bundler version to 1.10.3

app/views/cms/apis/categories/index.html.erb, app/views/cms/apis/groups/index.html.erb, app/views/cms/apis/pages/index.html.erb, app/views/contact/search_groups/index.html.erb, app/views/sys/apis/groups/index.html.erb, app/views/workflow/search_approvers/index.html.erb, config/routes/cms/routes_end.rb, config/routes/facility/routes.rb, config/routes/sys/routes.rb
=> search apis: remove { multipart: ture }

app/models/event/page.rb
=> event: add map addon to event page #482

app/models/concerns/ss/file/model.rb
=> resize image: use resize_to_fit #486

app/views/inquiry/agents/nodes/form/_form.html.erb
=> [#270] add label

app/controllers/inquiry/agents/nodes/form_controller.rb, app/models/inquiry/addon.rb, app/models/inquiry/answer.rb, app/models/inquiry/answer/data.rb, app/views/inquiry/agents/addons/input_setting/_form.html.erb, app/views/inquiry/agents/addons/input_setting/_show.html.erb, app/views/inquiry/agents/nodes/form/_form.html.erb, config/locales/inquiry/ja.yml
=> [#370] add input confirm field and validate it on submit.

Gemfile, Gemfile.lock
Include them in ss/script.coffee.erb and ss/style.scss.
ref. https://github.com/bokmann/fullcalendar-rails#installation
=> Use fullcalendar-rails 2.3.1.0 and momentjs-rails 2.10.2

app/views/workflow/agents/addons/branch/_show.html.erb, config/locales/workflow/ja.yml
workflow branch: fix locale #512
=> workflow branch: fix locale

app/models/ezine/page.rb, spec/factories/ezine/member.rb, spec/factories/ezine/node.rb, spec/models/ezine/page_spec.rb
=> Fix ezine page

app/controllers/concerns/cms/base_filter.rb, app/models/cms/addon/page_setting.rb, app/models/cms/site.rb, app/models/concerns/cms/addon.rb, app/views/cms/agents/addons/meta/_form.html.erb, app/views/cms/agents/addons/meta/_show.html.erb, app/views/cms/agents/addons/page_setting/_form.html.erb, app/views/cms/agents/addons/page_setting/_show.html.erb, app/views/cms/sites/_form.html.erb, config/locales/cms/ja.yml, config/locales/ss/ja.yml, spec/factories/cms/sites.rb
=> add meta setting #509

app/models/concerns/cms/group_permission.rb
Fix followings of `app/models/concerns/cms/group_permission.rb`
* Indent
* 2 `group_ids` arrays product calculation logic
=> Fix index and logic

app/views/facility/agents/nodes/page/index.html.erb, app/views/facility/temp_files/index.html.erb
=> facility: improve of image modal #505

app/controllers/cms/agents/tasks/pages_controller.rb, app/controllers/fs/files_controller.rb, app/models/concerns/cms/addon/file.rb, app/models/concerns/cms/content.rb, app/models/concerns/cms/model/page.rb, app/models/concerns/ss/model/file.rb, app/views/cms/agents/addons/file/_form.html.erb, app/views/facility/agents/addons/image/_form.html.erb, config/routes/cms/routes_end.rb, config/routes/fs/routes.rb, lib/migrations/ss/20150619114301_fix_ss_files_url.rb, lib/tasks/cms/page.rake, spec/fixtures/ss/migration/fix_ss_files_url/after.html, spec/fixtures/ss/migration/fix_ss_files_url/after_layout.html, spec/fixtures/ss/migration/fix_ss_files_url/before.html, spec/fixtures/ss/migration/fix_ss_files_url/before_layout.html, spec/lib/ss/migrations/20150619114301_fix_ss_files_url_spec.rb
=> add attachment_files option to cms:generate_pages

app/models/ads/part.rb, app/models/article/node.rb, app/models/article/page.rb, app/models/article/part.rb, app/models/category/node.rb, app/models/category/part.rb, app/models/cms/node.rb, app/models/cms/page.rb, app/models/cms/part.rb, app/models/event/node.rb, app/models/event/page.rb, app/models/ezine/node.rb, app/models/ezine/page.rb, app/models/facility/image.rb, app/models/facility/map.rb, app/models/facility/node.rb, app/models/faq/node.rb, app/models/faq/page.rb, app/models/faq/part.rb, app/models/inquiry/node.rb, app/models/member/node.rb, app/models/rss/node.rb, app/models/rss/page.rb, app/models/sitemap/node.rb, app/models/sitemap/page.rb, app/models/uploader/node.rb, app/models/urgency/node.rb
=> modify addon's order #556

app/models/ezine/task.rb
=> [ci skip] Fix also English comment

app/models/concerns/cms/model/member.rb
=> [disable] member model's email index

app/models/concerns/ss/relation/thumb.rb, app/models/ss/file.rb
=> [change] method name: has_many_thumbs to use_relation_thumbs

README.md
fix this error:
```
cp: omitting directory ‘config/samples/multiple-dbs’
```
=> [skip ci] fix readme

app/models/concerns/ss/relation/thumb.rb
1. need relation reload after thumbs.destroy_all
2. small refactoring
=> [fix] relation thumb

db/seeds/demo/files/css/_part.scss
=> fix ie8 web font issue

app/controllers/application_controller.rb
this support affects public site not only private/admin site.
=> [modified][#596] add yet another support.

.travis.yml
http://docs.travis-ci.com/user/caching/
=> travis ci enable bunlder cache

app/assets/javascripts/cms/lib/preview.coffee.erb, app/assets/stylesheets/cms/preview.scss, app/controllers/cms/preview_controller.rb, app/controllers/concerns/cms/base_filter.rb, app/controllers/concerns/mobile/public_filter.rb, app/helpers/cms/path_helper.rb, app/views/cms/contents/index.html.erb, app/views/cms/node/nodes/index.html.erb, app/views/cms/nodes/_show.html.erb, app/views/cms/nodes/index.html.erb, app/views/cms/pages/_show.html.erb, app/views/cms/pages/index.html.erb, app/views/facility/images/index.html.erb, app/views/facility/maps/index.html.erb, app/views/facility/pages/_menu.html.erb, app/views/facility/pages/index.html.erb, app/views/facility/searches/index.html.erb, app/views/urgency/layouts/index.html.erb, config/locales/cms/ja.yml, config/locales/ss/ja.yml, config/locales/urgency/ja.yml
mobileのプレビューリンクを管理画面に追加するPRです。
=> [add] mobile preview links in views

app/controllers/cms/preview_controller.rb
施設機能で公開画面にcolorboxを使っているので、プレビューでも対応できるようにタグを追加
=> [add] colorbox script tag in preview

app/controllers/cms/groups_controller.rb, app/controllers/cms/users_controller.rb, app/models/cms/group.rb, app/models/cms/user.rb, app/models/concerns/cms/addon/import/group.rb, app/models/concerns/cms/addon/import/user.rb, app/views/cms/groups/import.erb, app/views/cms/users/_menu.html.erb, app/views/cms/users/import.erb, config/locales/cms/ja.yml, config/locales/ja.yml, config/routes/cms/routes_end.rb, spec/features/cms/groups_spec.rb, spec/features/cms/users_spec.rb, spec/fixtures/cms/group/cms_groups_1.csv, spec/fixtures/cms/user/cms_users_1.csv
ユーザーとグループのCSVインポート/ダウンロードのPRです。
=> [add] user group import

config/locales/workflow/ja.yml
=> [fix] workflow locale

app/controllers/concerns/ss/auth_filter.rb, app/controllers/concerns/ss/base_filter.rb, app/controllers/fs/files_controller.rb, app/controllers/sns/apis/temp_files_controller.rb, app/models/concerns/cms/addon/file.rb, app/models/concerns/facility/addon/image.rb, app/models/concerns/ss/model/file.rb
=> [add] session check in Fs::FilesController

app/controllers/board/agents/nodes/post_controller.rb, app/controllers/cms/agents/tasks/nodes_controller.rb, app/controllers/cms/agents/tasks/pages_controller.rb, app/controllers/concerns/member/login_filter.rb, app/controllers/history/cms/logs_controller.rb, app/controllers/member/agents/nodes/login_controller.rb, app/controllers/sns/login_controller.rb, app/models/board/file.rb, app/models/board/post.rb, app/models/concerns/board/addon/file.rb, app/models/gws/schedule/plan_repeat.rb, app/models/gws/schedule/planable.rb, app/models/kana/dictionary.rb, spec/support/ss/http_server_support.rb
=> Tweak for rubocop

Gemfile.lock
tachikoma のPR #696 の一部でもあるのですけどこのgemの修正したの私でして，とりあえずこれがあると助かるので取り込んでもらえると嬉しいです．
=> [bump] "notiffany" gem version to 0.0.8

app/controllers/board/agents/nodes/post_controller.rb, app/models/board/file.rb, app/models/concerns/board/addon/file.rb, app/views/board/agents/nodes/post/sent.html.erb, config/locales/board/ja.yml
=> [fix] cms board

app/controllers/cms/agents/tasks/links_controller.rb
=> [fix] link check/expand dirname

app/models/concerns/ss/relation/file.rb
SS::Relation::Fileを使用している箇所で添付ファイルの公開状態を記事と連動させる処理です。
=> [fix] relation file state (ads, key_visual)

app/assets/javascripts/cms/lib/form.coffee.erb, app/controllers/cms/link_check_controller.rb
=> [modify] link check json format

app/models/concerns/ss/model/file.rb, config/defaults/environment.yml, lib/ss/filename_convertor.rb
日本語ファイル名の置換にIDを使用するオプションを加えました。
=> [add] sequence option in filename validation

app/controllers/sns/user_accounts_controller.rb, app/views/sns/user_accounts/edit.html.erb
アカウントの編集では以下の情報のみ変更できるようにしました。
* 氏名
* システム管理者
* メールアドレス
=> [fix] #762

app/controllers/concerns/cms/public_filter/layout.rb
=> [fix] yield parser on layout

spec/spec_helper.rb
This reverts commit a0945a0b758090535dfc9ac673936e62bbfc7119.
=> [modify] Enable Simplecov always

app/assets/javascripts/cms/lib/form.coffee.erb, app/controllers/application_controller.rb, app/controllers/cms/agents/parts/crumb_controller.rb, app/controllers/cms/agents/parts/tabs_controller.rb, app/controllers/cms/link_check_controller.rb, app/controllers/cms/preview_controller.rb, app/controllers/concerns/cms/public_filter/page.rb, app/controllers/sns/login_controller.rb, app/views/cms/agents/addons/body/_form.html.erb, config/defaults/environment.yml, config/locales/cms/ja.yml, config/routes/cms/routes_end.rb
以下を作成しました。
* csrfの設定
* 動的プレビュー機能
=> [add] form preview

Gemfile.lock
:hamster::hamster::hamster: <br /> <br /> Strategy bundler
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6082792786459465443">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6082792786459465443">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20151216072718

app/views/facility/agents/nodes/search/map.html.erb, app/views/map/agents/addons/page/_form.html.erb, app/views/map/agents/addons/page/_show.html.erb, app/views/map/agents/addons/page/view/index.html.erb
ref. SensorNotRequired: https://developers.google.com/maps/documentation/javascript/error-messages
=> [fix] remove sensor query at google map api

lib/mobile/converter.rb, spec/lib/mobile/converter_spec.rb
=> [fix] mobile #s_to_attr

README.md
=> [add] "--without development test" options

config/application.rb
MongoDB に問い合わせずに Mongoid でキャッシュする。
~~~
D, [2016-02-26T02:01:54.291190 #3653] DEBUG -- :   MOPED: 127.0.0.1:27017 QUERY        database=ss collection=ss_users selector={"$query"=>{"_id"=>2}, "$orderby"=>{"uid"=>1, "email"=>1}} flags=[] limit=0 skip=0 batch_size=nil fields=nil runtime: 0.4359ms
D, [2016-02-26T02:01:54.292564 #3653] DEBUG -- :   MOPED: 127.0.0.1:27017 QUERY        database=ss collection=ss_sites selector={"_id"=>1} flags=[] limit=0 skip=0 batch_size=nil fields=nil runtime: 0.2581ms
D, [2016-02-26T02:01:54.295241 #3653] DEBUG -- :   MOPED: 127.0.0.1:27017 QUERY        database=ss collection=cms_nodes selector={"site_id"=>1, "_id"=>206} flags=[] limit=0 skip=0 batch_size=nil fields=nil runtime: 0.5566ms
D, [2016-02-26T02:01:54.296540 #3653] DEBUG -- :   MOPED: 127.0.0.1:27017 …
=> Mongoid::QueryCache::Middleware

app/assets/javascripts/ss/lib/tree_ui.coffee, app/views/cms/groups/index.html.erb
=> [fix] cms group search

app/controllers/cms/agents/parts/crumb_controller.rb, app/controllers/concerns/cms/public_filter/layout.rb, lib/migrations/ss/20160225000000_fix_role_permissions.rb
C: Use reverse_each instead of reverse.each.
C: Assignment Branch Condition size for render_layout is too high. [63/61]
C: Method has too many lines. [49/42]
=> [fix] for rubocop

README.md, app/models/concerns/board/model/post.rb
=> [fix] README.md

Gemfile, Gemfile.lock, config/initializers/ss/escape_utils.rb
ERB::Util.html_escape 非互換による不具合 #841
=> [fix] remove gem 'escape_utils' #841

app/assets/javascripts/ss/script.coffee.erb, app/assets/stylesheets/ss/_pc_mb.scss, app/controllers/concerns/ss/auth_filter.rb, app/controllers/sns/login_controller.rb, app/controllers/sns/user_accounts_controller.rb, app/models/concerns/ss/model/user.rb, app/views/cms/agents/addons/release/_form.html.erb, app/views/cms/agents/addons/release_plan/_form.html.erb, app/views/cms/users/_form.html.erb, app/views/cms/users/_show.html.erb, app/views/ezine/agents/addons/deliver_plan/_form.html.erb, app/views/gws/users/_form.html.erb, app/views/gws/users/_show.html.erb, app/views/inquiry/agents/addons/reception_plan/_form.html.erb, app/views/inquiry/agents/addons/release_plan/_form.html.erb, app/views/layouts/ss/base.html.erb, app/views/sys/users/_form.html.erb, app/views/sys/users/_show.html.erb, config/locales/ss/ja.yml, spec/features/cms/users_spec.rb, spec/features/workflow/routes_spec.rb
- account_expiration
- initialize_password_warning
- and fix tags
=> [add] user / account_expiration #866

app/controllers/concerns/ss/auth_filter.rb, app/controllers/concerns/ss/base_filter.rb, app/controllers/ldap/import_controller.rb, app/controllers/ldap/server_controller.rb, app/controllers/sns/login_controller.rb, config/defaults/sns.yml, spec/features/cms/search_contents_spec.rb
* 管理画面のログイン情報の有効期限を設定した。
* 有効期限は `config/sns.yml` の `session_lifetime` で設定できる。
* `session_lifetime` の最大値は 1 時間。
* セッションにログイン時のパスワードを格納しているが、可能方法を少し変えた。
=> [modify] session expiration

app/controllers/application_controller.rb, db/seeds/demo/parts/map-side.part.html
[fix] webrick's no method error when HTTP_ORIGIN is not presented.
=> fix webrick no method error

app/models/cms/all_content.rb, config/locales/cms/ja.yml, spec/models/cms/all_content_spec.rb
Modify from .url to .full_url.
Modify ja locale of name.
Add index_name.
For the comment of #753:
https://github.com/shirasagi/shirasagi/issues/753#issuecomment-206192848
=> [fix] AllContent.csv #753

app/models/concerns/gws/board/descendants_file_info.rb, app/models/concerns/gws/board/postable.rb, app/models/concerns/gws/board/setting.rb, app/models/gws/board/post.rb, app/models/gws/board/topic.rb, app/views/gws/board/settings/_form.html.erb, app/views/gws/board/settings/_show.html.erb, config/locales/gws/board/ja.yml, spec/models/gws/board/post/descendants_file_info_spec.rb, spec/models/gws/board/post/file_size_limit_spec.rb, spec/spec_helper.rb, spec/support/gws/user.rb, spec/support/ss/tmp_dir_support.rb
=> limit attachment file size on board

app/assets/stylesheets/gws/style.scss, app/assets/stylesheets/ss/style.scss, app/models/concerns/gws/schedule/planable.rb, app/views/gws/schedule/plans/_form.html.erb
"25:00" が入力された場合、エラーになるようにしました。
=> schedule date validation

app/models/cms/notice.rb, app/models/concerns/board/model/post.rb, app/models/concerns/cms/addon/edit_lock.rb, app/models/concerns/cms/addon/release_plan.rb, app/models/concerns/cms/content.rb, app/models/concerns/cms/model/member.rb, app/models/concerns/ezine/addon/deliver_plan.rb, app/models/concerns/gws/addon/release.rb, app/models/concerns/gws/board/postable.rb, app/models/concerns/gws/schedule/planable.rb, app/models/concerns/inquiry/addon/reception_plan.rb, app/models/concerns/inquiry/addon/release_plan.rb, app/models/concerns/ss/model/group.rb, app/models/concerns/ss/model/task.rb, app/models/concerns/ss/model/user.rb, app/models/concerns/ss/model/user_title.rb, app/models/gws/facility/item.rb, app/models/gws/reminder.rb, app/models/gws/schedule/repeat_plan.rb, app/validators/datetime_validator.rb, spec/validators/datetime_validator_spec.rb
validates :field, datetime: true
=> Datetime validator

app/controllers/gws/share/settings_controller.rb, app/models/concerns/gws/share/setting.rb, app/models/concerns/ss/model/file.rb, app/models/gws/share/file.rb, app/models/gws/share/initializer.rb, app/views/gws/board/settings/_form.html.erb, app/views/gws/schedule/settings/_form.html.erb, app/views/gws/share/settings/_form.html.erb, app/views/gws/share/settings/_navi.html.erb, app/views/gws/share/settings/_show.html.erb, config/locales/gws/board/ja.yml, config/locales/gws/share/ja.yml, config/routes/gws/share/routes.rb, spec/models/gws/share/file/factory_girl_spec.rb, spec/models/gws/share/file/max_file_size_spec.rb, spec/support/gws/user.rb
=> share file limit

app/assets/javascripts/ss/lib/tree_ui.coffee, app/assets/stylesheets/ss/_pc_mb.scss, app/controllers/gws/apis/facilities_controller.rb, app/controllers/gws/apis/users_controller.rb, app/controllers/gws/board/apis/categories_controller.rb, app/controllers/gws/schedule/facilities_controller.rb, app/controllers/gws/share/apis/categories_controller.rb, app/models/concerns/gws/category/traversable.rb, app/models/gws/facility/category.rb, app/models/gws/facility/category_traverser.rb, app/models/gws/facility/item.rb, app/views/gws/apis/facilities/index.html.erb, app/views/gws/apis/users/index.html.erb, app/views/gws/board/apis/categories/index.html.erb, app/views/gws/board/topics/index.html.erb, app/views/gws/schedule/facilities/index.html.erb, app/views/gws/share/apis/categories/index.html.erb, app/views/gws/share/files/index.html.erb
グループドロップダウンを次のように改変してみました。
ドロップダウンをクリックすると、グループのツリーが表示されます。
=> ユーザー選択ダイアログのグループドロップダウンを改変

config/initializers/skip_mongoid_query_cache.rb, spec/lib/ss/ss_915_spec.rb
=> [add] skip mongoid query cache

app/assets/javascripts/gws/schedule/lib/calendar.coffee.erb, app/assets/javascripts/gws/schedule/lib/multiple_calendar.coffee.erb, app/assets/javascripts/ss/script.coffee.erb, spec/features/gws/board/topics/basic_crud_spec.rb, spec/features/gws/share/files_spec.rb, spec/features/gws/workflow/files/basic_crud_spec.rb
次のようにしました。
```
view.el.find(".fc-body").html("")
```
↓
```
view.el.find(".fc-body").hide()
```
IE9 - Win7 での動作を確認。
=> calendar next prev/button

app/controllers/gws/apis/facilities_controller.rb, app/controllers/gws/schedule/facilities_controller.rb, app/models/concerns/gws/category/traversable.rb, app/views/gws/board/topics/index.html.erb, app/views/gws/schedule/facilities/index.html.erb, app/views/gws/share/files/index.html.erb
colorbox 外のカテゴリー表示時に通常のドロップダウンを使用するようにしました。
=> [modify] to display categories dropdown, use normal dropdown instead of dropdown tree

.gitignore
For the common command "bundle install --path vendor/bundle".
=> [ignore] /vendor/bundle

app/controllers/ads/access_logs_controller.rb, app/controllers/board/posts_controller.rb, app/controllers/cms/all_contents_controller.rb, app/controllers/cms/groups_controller.rb, app/controllers/cms/members_controller.rb, app/controllers/cms/users_controller.rb, app/controllers/concerns/history/log_filter/view.rb, app/controllers/concerns/job/logs_filter.rb, app/controllers/concerns/voice/files_filter.rb, app/models/concerns/cms/model/member.rb, app/views/cms/members/_menu.html.erb, config/routes/cms/routes_end.rb
=> fix member search

public/assets/js/exif-js.js
use in member photo
ref: https://github.com/exif-js/exif-js
=> [add] exif-js

app/assets/javascripts/ss/lib/addon/markdown.coffee.erb, app/assets/stylesheets/gws/schedule/_gws.scss, app/controllers/sns/agents/addons/markdown_controller.rb, app/models/concerns/gws/reference/user.rb, app/models/concerns/ss/addon/markdown.rb, app/models/concerns/ss/model/user.rb, app/views/cms/users/index.html.erb, app/views/gws/schedule/custom_group_plans/index.html.erb, app/views/gws/schedule/group_plans/index.html.erb, app/views/gws/schedule/plans/popup.html.erb, app/views/gws/schedule/search_plans/index.html.erb, app/views/gws/users/index.html.erb, app/views/sns/user_accounts/_form.html.erb, app/views/sys/users/index.html.erb, config/locales/ss/ja.yml, config/routes/sns/routes.rb
- tel view
- markdown ajax preview
=> [modify] gws features

app/models/concerns/cms/model/layout.rb, app/models/concerns/cms/model/node.rb, app/models/concerns/cms/model/part.rb, spec/features/cms/move_spec.rb
https://github.com/shirasagi/shirasagi/blob/master/app/views/cms/apis/contents/html/index.html.erb#L81
=> [fix] page & node move features

app/assets/stylesheets/ss/_ckeditor.scss
=> [fix] ckeditor: fontsize text css

app/jobs/gws/reminder/notification_job.rb, lib/tasks/gws/reminder.rake
and add support fro integer style time
=> [gws][modify] round down seconds

app/models/concerns/gws/addon/release.rb
> WARN -- : Overwriting existing field state in class Gws::Board::Topic.
=> [refactor]  overwriting warn

app/controllers/cms/agents/nodes/archive_controller.rb, config/routes/cms/routes_end.rb
いつもお世話になっております。シオラボの大場です。
アーカイブナビゲーションにおける既存の問題点の修正をいたしましたのでPRさせていただきます。
=> 「アーカイブのナビゲーション」　の開発

app/controllers/cms/agents/nodes/archive_controller.rb, app/controllers/cms/agents/parts/calendar_nav_controller.rb, app/helpers/cms/archive_helper.rb, app/models/cms/initializer.rb, app/models/cms/part.rb, app/models/member/node.rb, app/views/cms/agents/parts/calendar_nav/index.html.erb, config/locales/cms/ja.yml, config/routes/cms/routes_end.rb, spec/factories/cms/parts.rb, spec/features/cms/agents/parts/calendar_nav_spec.rb
いつもお世話になっております。シオラボの大場です。
アーカイブ用のカレンダー表示ナビゲーションを開発いたしましたので、PRさせていただきます。ご確認をよろしくお願いいたします。
=> カレンダー表示ナビゲーションの開発

app/controllers/cms/agents/parts/monthly_nav_controller.rb, app/models/cms/initializer.rb, app/models/cms/part.rb, app/models/concerns/cms/addon/monthly_nav.rb, app/models/member/node.rb, app/views/cms/agents/addons/monthly_nav/_form.html.erb, app/views/cms/agents/addons/monthly_nav/_show.html.erb, app/views/cms/agents/parts/monthly_nav/index.html.erb, config/locales/cms/ja.yml, config/routes/cms/routes_end.rb, spec/factories/cms/parts.rb, spec/features/cms/agents/parts/monthly_nav_spec.rb
いつもお世話になっております。シオラボの大場です。
アーカイブ用の月次表示ナビゲーションを実装いたしましのでPRさせていただきます。
表示期間は、パーツ作成時に設定できるようにしています。
ご確認、よろしくお願い致します。
=> 月次表示ナビゲーションの開発

Gemfile.lock
see:
- https://github.com/mikanmarusan/omniauth-yahoojp/commit/7b8a198502fef7517291d2788c192f30006f8942
- https://github.com/intridea/omniauth-oauth2/issues/28
=> [fix] unable to oauth by yahoo

app/assets/javascripts/cms/public.coffee.erb, app/controllers/concerns/cms/public_filter/layout.rb, app/controllers/recommend/history/receiver_controller.rb, app/helpers/recommend/list_helper.rb, app/models/concerns/recommend/addon/content_list.rb, app/models/recommend/history/log.rb, app/views/recommend/agents/parts/history/index.erb
=> [modify] recommend history part

app/models/concerns/workflow/approver.rb, app/views/workflow/agents/addons/approver/_form.html.erb, app/views/workflow/agents/addons/approver/_show.html.erb, config/locales/workflow/ja.yml
承認申請を行い、同ユーザーで下書き保存をした際に、キャンセルとなるよう機能修正
=> [add] workflow_state: cancelled

app/helpers/ss/jbuilder_helper.rb, app/views/ss/crud/index.json.jbuilder, app/views/ss/crud/show.json.jbuilder
Mongoid の relation を自動で展開して、次の情報をレスポンスに含められるようになる拡張です。
```json
"categories": {
"82": {
"name": "お知らせ",
"filename": "oshirase",
"url": "/oshirase/",
"updated": "2016-10-31T16:10:26.518+09:00"
},
"83": {
"name": "イベント",
"filename": "oshirase/event",
"url": "/oshirase/event/",
"updated": "2016-10-28T19:12:15.147+09:00"
},
"127": {
"name": "組織案内",
"filename": "shisei/soshiki",
"url": "/shisei/soshiki/",
"updated": "2016-10-28T19:12:18.572+09:00"
},
"128": {
"name": "企画政策部",
"filename": "shisei/soshiki/kikaku",
"url": "/shisei/soshiki/kikaku/",
"updated": "2016-10-28T19:12:18.629+09:00"
}
},
```
```json
"files": {
"12": {
"name": "画像5",
"filename": "keyvisual05.jpg",
"url": "/fs/1/2/_/keyvisual05.jpg",
"content_type": "image/jpeg",
"updated": "2016-10-28T19:16:01.221+09:00"
},
"10": {
"name": …
```
=> [modify] contains extra nodes / files information in json response

app/controllers/concerns/cms/public_filter/open_graph.rb, app/controllers/concerns/cms/public_filter/twitter_card.rb, app/models/concerns/ss/addon/facebook_setting.rb, app/models/concerns/ss/addon/twitter_setting.rb, app/views/layouts/cms/_opengraph.html.erb, app/views/layouts/cms/_twitter_card.html.erb, app/views/ss/agents/addons/facebook_setting/_form.html.erb, app/views/ss/agents/addons/facebook_setting/_show.html.erb, app/views/ss/agents/addons/twitter_setting/_form.html.erb, app/views/ss/agents/addons/twitter_setting/_show.html.erb, config/locales/ss/ja.yml
=> [modify] OGP enhancement

app/views/inquiry/answers/_show.html.erb
Issue: 問い合わせフォームの回答が改行されていない #1365
=> [fix] inquiry / BR #1365

app/controllers/ezine/member_page/main_controller.rb
=> [modify] load_members

app/controllers/inquiry/answers_controller.rb, app/views/inquiry/answers/_show.html.erb, spec/features/article/pages/opendata_ref_basic_spec.rb, spec/features/inquiry/answers_spec.rb
お問合わせでカラムを削除すると、回答のダウンロードで 500 エラーになる障害の修正です。
=> [fix] 500 error on downloading inquiry answers

Gemfile, Gemfile.lock, app/models/article/page.rb, app/models/cms/page.rb, app/models/concerns/cms/addon/sns_poster.rb, app/models/concerns/ss/addon/facebook_setting.rb, app/models/concerns/ss/addon/twitter_setting.rb, app/models/event/page.rb, app/models/faq/page.rb, app/views/cms/agents/addons/sns_poster/_form.html.erb, app/views/cms/agents/addons/sns_poster/_show.html.erb, app/views/ss/agents/addons/facebook_setting/_form.html.erb, app/views/ss/agents/addons/facebook_setting/_show.html.erb, app/views/ss/agents/addons/twitter_setting/_form.html.erb, app/views/ss/agents/addons/twitter_setting/_show.html.erb, config/locales/cms/ja.yml, config/locales/sns_poster/ja.yml, config/locales/ss/ja.yml
=> [Fix]Features/sns_post

.travis.yml, README.md, bin/install.sh
=> Ruby 2.3.4

app/controllers/application_controller.rb, app/controllers/cms/preview_controller.rb, app/controllers/concerns/cms/public_filter.rb, app/controllers/concerns/ss/base_filter.rb, app/controllers/fs/files_controller.rb
this commit also fixes unable to update 404.html.
=> [fix] error pages like 404.html is treated as ERB.

app/controllers/webmail/apis/imap_controller.rb, app/models/webmail/imap/quota.rb, config/defaults/webmail.yml
=> [Webmail] disable_quota setting

db/seeds/childcare/files/css/_init.scss
=> [fix] seed/childcare - animation mixins

README.md, bin/install.sh
#1556 対応のプルリクエストです。
お手数ですがよろしくお願いいたします。
=> [modify] install.sh / README.md

app/controllers/cms/all_contents_controller.rb, app/models/cms/all_content.rb
- to improve use interaction
- to reduce memory consumption
=> [modify] use send_enum instead of send_data

app/controllers/concerns/cms/public_filter.rb, app/controllers/concerns/kana/public_filter.rb, app/controllers/concerns/mobile/public_filter.rb
=> /kanaと/mobileをサブサイトディレクトリ配下に移動する修正

app/controllers/cms/agents/tasks/nodes_controller.rb, lib/tasks/cms/page.rake, lib/tasks/rss/page.rake
フォルダーを指定してフォルダーを書き出した場合、そのフォルダーしか書き出されません。
直感に反する動作ですので、プルリクを送ります。
=> 再帰的フォルダー書き出し

app/mailers/application_mailer.rb
And authentication should be symbol
=> [fix] deliver_method must be symbol.

db/seeds/gws/contents.rb, db/seeds/gws/load.rb, db/seeds/lp/load.rb, db/seeds/ss/users.rb, lib/ss/db/seed.rb, spec/features/gws/board/topics/basic_crud_spec.rb, spec/features/gws/custom_groups_spec.rb, spec/features/gws/faq/topics/basic_crud_spec.rb, spec/features/gws/qna/topics/basic_crud_spec.rb
[refactor] db/seed for rubocop
=> [GWS][refactor] db/seed for rubocop

app/assets/javascripts/gws/schedule/lib/todo.coffee.erb, app/controllers/gws/schedule/todo_management_controller.rb, app/controllers/gws/schedule/todos_controller.rb, app/helpers/gws/schedule/plan_helper.rb, app/helpers/gws/schedule/todo_helper.rb, app/models/gws/schedule/todo.rb, app/views/gws/schedule/todo_management/_list_head.html.erb, app/views/gws/schedule/todo_management/_menu.html.erb, app/views/gws/schedule/todo_management/index.html.erb, app/views/gws/schedule/todo_management/recover.html.erb, app/views/gws/schedule/todos/_form.html.erb, app/views/gws/schedule/todos/_menu.html.erb, app/views/gws/schedule/todos/_show.html.erb, app/views/gws/schedule/todos/delete.html.erb, config/locales/gws/schedule/ja.yml, config/routes/gws/schedule/routes.rb, spec/features/gws/schedule/todos_spec.rb, spec/helpers/gws/schedule/todo_helper_spec.rb, spec/jobs/gws/schedule/todo_job_spec.rb
ToDo機能につきましてレビューでご指摘のありました点の対応及びテストの追加を行いました。
お手数ですがレビューをお願いいたします。
=> [modify] gws/todo feature

app/helpers/gws/schedule/plan_helper.rb, app/models/gws/schedule/todo.rb, app/views/gws/schedule/todo_management/_menu.html.erb, app/views/gws/schedule/todos/_form.html.erb, spec/helpers/gws/schedule/todo_helper_spec.rb, spec/jobs/gws/schedule/todo_job_spec.rb
ToDo機能につきましてレビューでご指摘のありました点の対応及びテストの修正を行いました。
お手数ですがレビューをお願いいたします。
=> [modify] gws/todo feature 

app/models/gws/circular/post.rb, app/views/gws/circular/apis/categories/index.html.erb, app/views/gws/circular/posts/_form.html.erb
=> [GWS] circular minor issues

app/controllers/gws/memo/comments_controller.rb, app/views/gws/agents/addons/memo/comments/_show.html.erb
連絡メモ機能についてマージいただいた直後に申し訳ありません。
フォルダー内でコメントが削除できない不具合を修正しました。
大変お手数ですが、レビューと取り込みをお願いいたします。
=> [modify] available delete comment in folder

app/assets/javascripts/ss/script.coffee.erb, vendor/assets/packages/starts-with/LICENSE-MIT.txt, vendor/assets/packages/starts-with/README.md, vendor/assets/packages/starts-with/package.json, vendor/assets/packages/starts-with/startswith.js
IE11 and IE9 doesn't have `startsWith`.
This is polyfill.
=> [add] startsWith polyfill

app/assets/stylesheets/gws/memo/_gws.scss, app/assets/stylesheets/ss/_lib.scss, app/assets/stylesheets/ss/_pc_mb.scss, app/assets/stylesheets/webmail/_ss.scss, app/models/gws/share/folder.rb, app/views/gws/memo/messages/_content_navi.html.erb, app/views/gws/share/files/_content_navi.html.erb, app/views/webmail/main/_navi.html.erb, config/locales/ss/ja.yml
- memo/quota
- share/quota
- webmail/quota
=> [refactor] integrate quota views into ss-quota-bar

app/controllers/concerns/gws/memo/notification_filter.rb, app/models/concerns/gws/addon/system/menu_setting.rb, app/models/gws/memo/notifier.rb, app/views/gws/main/_navi.html.erb, config/locales/gws/board/ja.yml, config/locales/gws/faq/ja.yml, config/locales/gws/memo/ja.yml, config/locales/gws/qna/ja.yml, config/locales/gws/schedule/ja.yml
=> [modify] gws/memo/notification

app/controllers/gws/schedule/csv_controller.rb, app/models/gws/schedule/plan_csv/importer.rb, app/views/gws/schedule/csv/index.html.erb, config/locales/gws/schedule/ja.yml
=> [fix] gws/schedule: import csv

app/models/cms/column/value/base.rb, app/models/cms/column/value/file_upload.rb, app/models/concerns/cms/addon/form/page.rb, app/models/concerns/workflow/addon/branch.rb, spec/factories/cms/column/file_uploads.rb, spec/factories/cms/column/text_fields.rb, spec/factories/cms/forms.rb, spec/features/article/pages/clone_with_form_spec.rb
=> [add][cms] formed page clone

app/controllers/gws/share/apis/folders_controller.rb, app/controllers/gws/share/files_controller.rb, app/controllers/gws/share/management/files_controller.rb
* [fix] gws/share: sub_folders criteria
=> [fix] gws/share: sub_folders

app/assets/stylesheets/ss/_pc_mb.scss, app/views/layouts/service/base.html.erb, app/views/layouts/service/login.html.erb, app/views/layouts/ss/base.html.erb, config/defaults/ss.yml
and fix log was disappeared when gws/contrast was applied.
=> [add] `SS.config.ss.application_logo_html`

app/controllers/opendata/dataset/datasets_controller.rb, app/models/concerns/opendata/dataset_copy.rb, app/models/opendata/dataset.rb, app/models/opendata/url_resource.rb, config/routes/opendata/dataset/routes.rb, spec/factories/opendata/pages.rb, spec/features/opendata/dataset/datasets_spec.rb, spec/models/opendata/dataset_spec.rb
=> [add] opendata/dataset copy

Gemfile.lock, app/models/concerns/cms/model/member.rb, app/models/concerns/member/addon/yahoo_jp_oauth_v2.rb, app/models/member/node.rb, app/views/member/agents/addons/yahoo_jp_oauth_v2/_form.html.erb, app/views/member/agents/addons/yahoo_jp_oauth_v2/_show.html.erb, config/defaults/oauth.yml, config/initializers/oauth.rb, config/locales/member/ja.yml, db/seeds/opendata/files/css/style.scss
コールバックURL:  `http://$domain:$port/auth/yahoojp_v2/callback`
=> [add] yahoo oauth v2 provider

app/models/concerns/webmail/mail/message.rb, app/models/concerns/webmail/mail/parser.rb, app/views/webmail/mails/_menu.html.erb
- Encoding
- Blank email
- Replay from child mailbox
=> [fix] webmail: reply error

app/controllers/opendata/agents/tasks/node/search_datasets_controller.rb, app/models/concerns/opendata/dataset_searchable.rb, app/views/opendata/agents/nodes/dataset/search_dataset/index.html.erb, app/views/opendata/agents/nodes/dataset/search_dataset/search.html.erb
and also adds dataset search form preview support
=> [fix][opendata] unable to search dataset by dataset group

app/models/concerns/cms/addon/sns_poster.rb, app/models/concerns/ss/addon/facebook_setting.rb, app/views/ss/agents/addons/facebook_setting/_form.html.erb, app/views/ss/agents/addons/facebook_setting/_show.html.erb, config/locales/ss/ja.yml
- add `facebook_max_text_length` option to control text length
- add `facebook_appends_here_state` and `facebook_appends_here_prefix` to control "here" information
=> [add] some facebook auto poster options

app/assets/javascripts/cms/preview.coffee.erb, app/assets/javascripts/cms/public.coffee.erb, app/controllers/cms/preview_controller.rb, app/controllers/concerns/cms/public_filter/layout.rb, app/controllers/concerns/mobile/public_filter.rb, app/models/concerns/ss/addon/kana_setting.rb, app/models/concerns/ss/addon/mobile_setting.rb, app/models/concerns/ss/model/site.rb, config/initializers/mobile_support.rb
=> [fix] subdir filter location

app/models/concerns/ss/fields/normalizer.rb, spec/models/gws/system/menu_setting_spec.rb
improve localized field normalization.
=> [fix] gws: all menus are disappeare

bin/install.sh, bin/unicorn-centos7.service
インストーラで以下に対応しました。
・ＬＰサンプルを追加しました。
・GPG鍵のインストール失敗等でRubyがインストールできなかった場合は、処理を中断するようにしました。
・動的ページ生成で404エラーが発生した場合に、正常なステータスが返却できなかった不具合に対応しました。
・Javascriptのコンパイルに対応しました。
・unicorn起動タイムアウト値を調整しました。(1m30s->3m)
=> [modify] bin/install.sh

app/controllers/concerns/cms/crud_filter.rb, app/controllers/concerns/cms/page_filter.rb, app/controllers/gws/workflow/pages_controller.rb, app/controllers/workflow/pages_controller.rb, app/mailers/workflow/mailer.rb, app/models/concerns/workflow/approver.rb, app/views/workflow/agents/addons/approver/_show.html.erb, app/views/workflow/wizard/approver_setting_multi.html.erb, config/routes/workflow/routes.rb, spec/features/workflow/branch_spec.rb, spec/features/workflow/multi_stage_spec.rb, spec/features/workflow/pull_up_spec.rb
多段承認利用時、一つの段に複数のユーザーが設定されている場合、
全員が承認しても、次の段へ進まない障害の修正。
=> [fix] unable to step forward if multiple users are in a stage

app/assets/javascripts/webmail/lib/mail.coffee.erb, app/assets/stylesheets/gws/schedule/_gws.scss, app/views/webmail/mails/_menu.html.erb, app/views/webmail/mails/show.html.erb
- address helper
- callendar css
=> [modify] webmail: direct memo forwarding and fixes (m39)

app/controllers/gws/apis/users_controller.rb, app/controllers/gws/schedule/custom_group_plans_controller.rb, app/controllers/gws/schedule/group_plans_controller.rb, app/controllers/gws/schedule/search/users_controller.rb, app/controllers/gws/schedule/user_plans_controller.rb, app/models/concerns/gws/addon/readable_setting.rb, app/models/gws/user.rb
- readable_users
- readable_user?
=> [modify] gws/user: readable setting (m54)

app/views/webmail/gws_messages/_menu.html.erb, app/views/webmail/gws_messages/new.html.erb
=> [fix] webmail: back to mailbox on forwarding (m55)

app/jobs/gws/notice_notification_job.rb, app/views/gws/agents/addons/notice/notification/_form.html.erb, app/views/gws/agents/addons/notice/notification/_show.html.erb, spec/factories/board/anpi_posts.rb, spec/factories/chorg/revisions.rb, spec/jobs/gws/notice_notification_job_spec.rb, spec/spec_helper.rb
=> [fix] gws notice time

app/views/garbage/agents/addons/category/_form.html.erb
=> [fix] garbage : undefined @cur_node

.rubocop.yml, .rubocop_todo.yml, app/controllers/gws/report/columns_controller.rb, app/controllers/gws/report/trashes_controller.rb, app/controllers/inquiry/agents/nodes/form_controller.rb, app/models/concerns/gws/board/browsing_state.rb, app/models/concerns/gws/qna/browsing_state.rb, app/models/gws/group.rb, app/models/inquiry/answer.rb, app/models/opendata/dataset_group.rb, app/views/cms/agents/addons/additional_info/_form.html.erb, app/views/gws/agents/addons/member/_form.html.erb, app/views/gws/agents/addons/report/column_setting/_show.html.erb, app/views/gws/agents/columns/check_box/_column_form.html.erb, app/views/gws/agents/columns/file_upload/_column_form.html.erb, app/views/gws/agents/columns/file_upload/_column_show.html.erb, app/views/gws/agents/columns/radio_button/_column_form.html.erb, app/views/gws/agents/columns/text_area/_column_show.html.erb, app/views/gws/agents/columns/url_field/_column_form.html.erb, app/views/opendata/idea/comments/index.html.erb, app/views/sys/apis/groups/index.html.erb
従来からある不具合の修正や、Rails5 対応により発生している警告の修正
=> [fix] several issues

app/views/webmail/account_settings/_form.html.erb
test connection twice or more if there are multiple imap account settings
=> [fix][webmail] test connection twice or more

app/controllers/concerns/gws/staff_record/public_yearly_filter.rb, spec/features/gws/staff_record/public_records_spec.rb
=> [fix][gws] staff record multi tenant issue

app/controllers/gws/memo/export_messages_controller.rb, app/jobs/gws/memo/message_export/zip.rb, app/jobs/gws/memo/message_export_job.rb, app/views/gws/memo/export_messages/index.html.erb, config/locales/gws/memo/ja.yml, spec/features/gws/memo/messages/export_messages_spec.rb
メッセージのエクスポートをeml形式で出力できるようにしました。
よろしくお願いします。
=> [add][gws] export message as eml

app/assets/javascripts/gws/script.js.erb, app/assets/stylesheets/gws/style.scss, app/controllers/gws/portal/apis/temp_files_controller.rb, app/models/concerns/gws/addon/link_file.rb, app/models/concerns/gws/addon/portal/portlet/ad.rb, app/models/concerns/gws/portal/portlet_model.rb, app/models/concerns/ss/model/link_file.rb, app/models/gws/portal/group_setting.rb, app/models/gws/portal/user_setting.rb, app/models/ss/link_file.rb, app/views/gws/agents/addons/link_file/_form.html.erb, app/views/gws/agents/addons/link_file/_show.html.erb, app/views/gws/agents/addons/portal/portlet/ad/_form.html.erb, app/views/gws/agents/addons/portal/portlet/ad/_show.html.erb, app/views/gws/portal/apis/ajax_files/edit.html.erb, app/views/gws/portal/apis/ajax_files/index.html.erb, app/views/gws/portal/apis/ajax_files/new.html.erb, app/views/gws/portal/apis/ajax_files/select.html.erb, app/views/gws/portal/portlets/ad/index.html.erb, config/defaults/gws.yml, config/locales/gws/ja.yml, config/locales/gws/portal/ja.yml, config/routes/gws/portal/routes.rb
=> [add] ad portlet

app/controllers/gws/memo/notices_controller.rb, app/jobs/gws/notice/notification_job.rb, app/jobs/gws/report/notification_job.rb, app/jobs/gws/survey/notification_job.rb, app/models/gws/circular/post.rb, app/models/gws/discussion/post.rb, app/models/gws/discussion/topic.rb, app/models/gws/memo/notice.rb, app/models/gws/memo/notifier.rb, app/views/gws/agents/addons/notice/notification/_form.html.erb, app/views/gws/agents/addons/notice/notification/_show.html.erb, config/locales/gws/schedule/ja.yml, lib/migrations/gws/20181024000000_fix_gws_memo_notices.rb, spec/features/gws/schedule/plans/notification_spec.rb, spec/jobs/gws/notice/notification_job_spec.rb
=> add_notify_settings

app/controllers/application_controller.rb
see:
- https://qiita.com/rorensu2236/items/638d181e155b5dc5e35c
- https://developer.mozilla.org/ja/docs/Web/HTTP/Headers/Content-Disposition
=> [fix] japanese filename corruption

app/assets/javascripts/ss/script.js.erb, app/assets/stylesheets/ss/_login.scss, app/assets/stylesheets/ss/style.scss, app/controllers/concerns/sys/link_filter.rb, app/controllers/sys/ads_controller.rb, app/controllers/sys/apis/temp_files_controller.rb, app/models/concerns/ss/addon/link_file.rb, app/models/concerns/ss/model/link_file.rb, app/models/concerns/sys/ad.rb, app/models/sys/setting.rb, app/views/sns/login/_ad.html.erb, app/views/sns/login/login.html.erb, app/views/ss/agents/addons/link_file/_form.html.erb, app/views/ss/agents/addons/link_file/_show.html.erb, app/views/sys/ads/_form.html.erb, app/views/sys/ads/_show.html.erb, app/views/sys/apis/ajax_files/edit.html.erb, app/views/sys/apis/ajax_files/index.html.erb, app/views/sys/apis/ajax_files/new.html.erb, app/views/sys/apis/ajax_files/select.html.erb, config/locales/ss/ja.yml, config/locales/sys/ja.yml, config/routes/sys/routes.rb, spec/features/sns/ad_spec.rb, spec/features/sys/ad_spec.rb, spec/support/ss/tmp_dir_support.rb
=> [add] login ad

README.md, bin/install.sh
RVM GPG key acquisition method change
=> [modify] bin/install.sh README.md

app/controllers/gws/staff_record/users_controller.rb, app/models/concerns/gws/export.rb, app/models/concerns/webmail/address_export.rb, app/models/gws/staff_record/user.rb, app/views/gws/staff_record/users/_menu.html.erb, app/views/gws/staff_record/users/download.html.erb, config/locales/gws/ja.yml, config/routes/gws/staff_record/routes.rb
- `group_ids`, `user_ids` and `permission_level` export and import support
- UTF-8 CSV support
=> [gws][add] some staff record csv extensions

app/assets/stylesheets/cms/_column.scss, app/views/cms/agents/columns/table/_column_form.html.erb, app/views/cms/agents/columns/table/_table_editor.html.erb
表で、テキストエリアが出たり消えたりする件を改善してみました。
よろしくお願いします。
=> [fix] cms column: table textarea

app/controllers/cms/apis/forms_controller.rb, app/models/cms/column/value/youtube.rb, app/views/cms/agents/columns/youtube/_column_form.html.erb, app/views/cms/agents/columns/youtube/_column_show.html.erb
- now `url` is accessor.
- also remove `iframe` field which is redundant.
=> [fix] excludes `url` from link check by removing `url` field

app/controllers/concerns/cms/public_filter/layout.rb, app/controllers/concerns/mobile/public_filter.rb, app/controllers/concerns/ss/agent_filter.rb
=> [fix] preview_path? returns false even on preview

app/views/cms/agents/columns/table/_table_editor.html.erb, config/locales/cms/ja.yml
表の列と行の追加について修正しました。
ご確認、よろしくお願いします。
=> [fix] cms column: table editor append

app/assets/stylesheets/cms/_column.scss, app/models/cms/column/url_field2.rb, app/models/cms/column/value/url_field2.rb, app/views/cms/agents/columns/url_field2/_column_form.html.erb, app/views/cms/agents/columns/url_field2/_column_show.html.erb, config/locales/cms/ja.yml, db/seeds/cms/contents/articles.rb, db/seeds/demo/layout/1.layout.html, db/seeds/demo/layout/10.layout.html, db/seeds/demo/layout/11.layout.html, db/seeds/demo/layout/12.layout.html, db/seeds/demo/layout/2.layout.html, db/seeds/demo/layout/3.layout.html, db/seeds/demo/layout/4.layout.html, db/seeds/demo/layout/5.layout.html, db/seeds/demo/layout/7.layout.html, db/seeds/demo/layout/8.layout.html, db/seeds/demo/layout/9.layout.html
- add link target
- add internal managed link support
=> [add] cms/column/url_field2 enhancement

app/models/cms/column/value/url_field2.rb, app/models/cms/column/value/youtube.rb, app/views/cms/agents/columns/url_field2/_column_form.html.erb, app/views/cms/agents/columns/youtube/_column_show.html.erb
youtube_id and link_url is lost at merging branch
=> [fix] issues at merging branch

app/assets/javascripts/ss/lib/html_message.js.erb, app/assets/javascripts/ss/script.js.erb, app/assets/javascripts/webmail/lib/mail.js.erb, app/views/gws/memo/messages/_show.html.erb
and adds show image link to top of message
=> [modify][gws] show html message without CKEditor

app/models/concerns/cms/addon/form/page.rb, app/models/concerns/ss/file_factory.rb, spec/models/article/page_spec.rb
fix unexpected "generate_public_files" method override
=> [fix] relation file output is not working at publishing page

app/assets/javascripts/cms/preview/main.js.erb
that is inconvenient for touch devices
=> [modify] remove unnecessary overlay hide logic

app/models/concerns/cms/addon/import/user.rb, app/models/concerns/ss/model/user.rb, app/models/concerns/ss/user_import_validator.rb, app/models/concerns/sys/addon/role.rb, app/models/concerns/sys/reference/role.rb, app/models/gws/user_csv/exporter.rb, app/models/gws/user_csv/importer.rb, app/models/webmail/user_export.rb, config/locales/ja.yml, spec/features/gws/users_spec.rb, spec/features/webmail/users/import_spec.rb
=> [modify] webmail and gws import validation

app/controllers/gws/circular/admins_controller.rb, app/controllers/gws/circular/posts_controller.rb, app/controllers/gws/circular/trashes_controller.rb, app/models/concerns/gws/circular/sort.rb, app/models/gws/circular/post.rb, app/views/gws/circular/admins/index.html.erb, app/views/gws/circular/posts/index.html.erb, app/views/gws/circular/trashes/index.html.erb, config/locales/gws/circular/ja.yml
=> [modify] gws/circular created_at updated_at and sort by due_date

app/controllers/concerns/gws/staff_record/public_yearly_filter.rb, app/controllers/gws/staff_record/public_duties_controller.rb, app/controllers/gws/staff_record/public_records_controller.rb, app/jobs/gws/staff_record/copy_situation_job.rb, app/views/gws/staff_record/public_duties/_search.html.erb, app/views/gws/staff_record/public_records/_search.html.erb, config/initializers/mongoid.rb, db/seeds/gws/contents/staff_record.rb, spec/jobs/gws/staff_record/copy_situation_job_spec.rb
=> [modify] gws/staffrecord set the default as belonging group

app/models/concerns/gws/group_permission.rb, spec/factories/gws/roles.rb, spec/models/gws/group_permission_spec.rb
=> [fix][gws] custom group support of Gws::GroupPermission#owned?

app/models/cms/elasticsearch/searcher.rb, db/seeds/childcare/files/css/style.scss, db/seeds/childcare/load.rb, db/seeds/cms/contents/nodes.rb, db/seeds/company/files/css/style.scss, db/seeds/company/load.rb, db/seeds/demo/files/css/style.scss
=> [modify] db:seed for site_search

Gemfile, spec/spec_helper.rb
- bin/rails s
- before: 12 秒, 12 秒, 13 秒
- after: 6 秒, 7 秒, 7 秒
- bin/rake unicorn:start
- before: 20 秒, 19 秒, 19 秒
- after: 12 秒, 12 秒, 13 秒
=> [modify] stop loading redundant gems on development

.codeclimate.yml, .travis.yml, app/models/concerns/opendata/addon/zip_dataset.rb, spec/features/gws/survey/basic_crud_spec.rb, spec/features/gws/survey/categories_spec.rb, spec/features/gws/survey/trashes_spec.rb, spec/spec_helper.rb, spec/support/ss/capybara_support.rb, spec/support/ss/js_support.rb
- [modify] cache: assets
- [keep] Coveralls.wear!
- [add] CodeClimate
=> [update] Coveralls and CodeClimate

config.ru
unicorn worker killerのパラメータを環境変数参照としました。（デフォルト値は変更なし）
=> [modify] Unicorn WorkerKiller Parameter

app/views/sns/mypage/index.html.erb, spec/factories/sys/roles.rb, spec/features/sns/mypage_spec.rb
upon a user who has no permissions to use
=> [fix] able to see link to cms, gws or webmail

app/controllers/rss/agents/pages/page_controller.rb, app/models/concerns/rss/addon/page/body.rb, app/views/rss/agents/addons/page/body/view/index.html.erb, app/views/rss/agents/pages/page/index.html.erb, spec/models/rss/page_spec.rb
=> [cms][fix] full_url returns nil on some edge cases

lib/tasks/cms/es.rake, lib/tasks/opendata/resource.rake, lib/tasks/recommend/score.rake, lib/tasks/ss/daily.rake, lib/tasks/ss/hourly.rake, lib/tasks/ss/timely.rake, spec/jobs/cms/elasticsearch/indexer/page_release_job_spec.rb
default cron 
- daily.rake
- hourly.rake
- timely.rake
=> [add] hourly task

app/views/inquiry/agents/addons/feedback_setting/_form.html.erb, app/views/inquiry/agents/addons/feedback_setting/_show.html.erb
https://demo.ss-proj.org/.s1/cms/parts/48
上部HTML、下部HTML のテキストエリアが編集できてしまう問題を修正。
=> [fix] addons feedback_setting html readonly

app/jobs/history/history_log/purge_job.rb, app/jobs/history/history_log/trash_purge_job.rb, app/models/concerns/history/model/data.rb, config/defaults/ss.yml, config/locales/history/ja.yml, lib/tasks/history/history_log.rake, lib/tasks/ss/daily.rake, spec/jobs/history/history_log/trash_purge_job_spec.rb
=> [add][#3177] added history log deletion to daily tasks

app/jobs/gws/memo/message_export_job.rb, app/jobs/gws/notice/notification_job.rb, app/jobs/gws/survey/notification_job.rb, app/mailers/gws/memo/mailer.rb, app/views/gws/agents/addons/system/group_setting/_form.html.erb, app/views/gws/agents/addons/system/group_setting/_show.html.erb, config/defaults/gws.yml, spec/models/article/page_spec.rb
and then use these to generate full url
=> [fix][#3374] add default gws scheme and domain

app/views/ss/crud/ajax_files/index.html.erb, spec/features/gws/notices/resource_limitation_spec.rb, spec/features/webmail/mails/eml_attachment_spec.rb, spec/features/webmail/mails/sjis_attachment_spec.rb, spec/features/webmail/mails/unk_ext_attachment_spec.rb, spec/features/webmail/mails/zip_attachment_spec.rb
=> [modify] able to click by name on file modal

config/locales/voice/ja.yml, lib/voice/open_jtalk.rb
=> [add][cms][voice] path info to exception message

spec/features/cms/search_contents_spec.rb
and also eliminate japanese texts.
=> [modify][cms] stabilize specs up by completely waiting ajax

app/jobs/event/ical/import_job.rb, app/jobs/rss/import_job.rb, lib/tasks/event/page.rake, lib/tasks/rss/page.rake, spec/jobs/event/ical/import_job_spec.rb, spec/jobs/rss/import_job_spec.rb
and also fix that job daemon processes is increasing every ss:hourly if job mode set to "service"
=> [fixup] avoid rushing / running out memory

app/jobs/concerns/opendata/resource_report_base.rb
to generate reports from all histories
=> [fix][opendata] remove "resource_source_url: false" constraint 

app/assets/javascripts/map/googlemaps/form.js.erb, app/assets/javascripts/map/googlemaps/map.js.erb, app/helpers/map/map_helper.rb, app/views/opendata/agents/nodes/dataset/resource/googlemaps/map_content.html.erb
by initializing google map lazily.
=> [fix][cms][#3597] google map zoom level reset issue

app/assets/stylesheets/gws/survey/_gws.scss, app/views/gws/survey/editable_files/_summary.html.erb, app/views/gws/survey/editable_files/index.html.erb, app/views/gws/survey/files/_abstract.html.erb
=> [add][gws][survey] "name" and "description" to table and summary

Gemfile, Gemfile.lock, app/views/member/agents/nodes/login/login.html.erb
https://github.com/omniauth/omniauth/wiki/Resolving-CVE-2015-9284
=> [fix][cms/opendata] omnioauth's CVE 2015 9284

app/controllers/sns/login/open_id_connect_controller.rb, app/controllers/sns/login/saml_controller.rb, app/models/ss/sso_token.rb, app/models/sys/auth/open_id_connect/implicit_flow_response.rb, app/models/sys/auth/open_id_connect/token_request.rb, app/models/sys/auth/open_id_connect/token_response.rb, lib/tasks/ss/daily.rake, lib/tasks/ss/delete_access_tokens.rake, spec/models/ss/sso_token_spec.rb
this is introduced by @2d71c4294b7ec4cdb60d369a722e3ae158ea1811
=> [fix] saml login with "lax" same_site cookie setting

app/assets/javascripts/cms/lib/editor.js, app/helpers/ss/editor_helper.rb, app/views/cms/public_notices/show.html.erb, app/views/sns/public_notices/show.html.erb, spec/features/cms/notice/link_click_spec.rb, spec/features/sys/notice/link_click_spec.rb
参考: https://dev.ckeditor.com/ticket/7145
=> [fix] unable to open href on cms/notice

app/views/kaminari/_first_page.html.erb, app/views/kaminari/_gap.html.erb, app/views/kaminari/_last_page.html.erb, app/views/kaminari/_next_page.html.erb, app/views/kaminari/_page.html.erb, app/views/kaminari/_paginator.html.erb, app/views/kaminari/_prev_page.html.erb
Issue課題を全て終えたので、ご確認のほどよろしくお願い致します。
（但し、すでに対応されていた#3448については手を付けておりません。）
=> ページャnavタグのrole属性の削除

bin/install.sh
- https://qastack.jp/server/515957/how-to-have-nginx-forward-the-http-x-forwarded-proto-header
- https://serverfault.com/questions/515957/how-to-have-nginx-forward-the-http-x-forwarded-proto-header/859008
=> [modify] add support for load balancers, secure firewalls and etc

app/controllers/concerns/cms/public_filter/open_graph.rb, app/controllers/concerns/cms/public_filter/twitter_card.rb
[modified] og:descriptionとtwitter:descriptionの内容を統一  #3448
=> [modified] og:descriptionとtwitter:descriptionの内容を統一  #3448

app/models/faq/page.rb
FAQ/FAQ記事検索 ページに「エディタ設定」を追加しました。
=> [modified] 【CMS不具合】フォルダー：FAQ/FAQ記事検索 「エディタ設定」の追加

app/controllers/cms/agents/nodes/archive_controller.rb
アーカイブのフォルダ詳細画面からプレビューができない #3813
`Cms::Agents::Nodes::ArchiveController`の`redirect_to_archive_index`アクション内にpreviewパスを追加。
=> [fixes] add preview path to be able to preview archive #3813

app/jobs/cms/elasticsearch/indexer/page_release_job.rb, app/models/cms/elasticsearch/page_convertor.rb, app/models/cms/elasticsearch/page_convertor/opendata_app.rb, app/models/cms/elasticsearch/page_convertor/opendata_dataset.rb
=> [modify] cms/elasticsearch/indexer : opendata_dataset and opendata_app convertor

app/views/urgency/layouts/index.html.erb, spec/features/urgency/layouts_spec.rb
if mobile site setting has disabled
=> [fix][#3895] unable to open urgency folder

app/views/cms/agents/nodes/archive/index.html.erb
=> [modify] Display of year and month

app/models/cms/node.rb, app/models/concerns/cms/addon/list.rb, app/views/cms/agents/addons/page_list/_form.html.erb
K03012-312 【CMS不具合】写真一覧フォルダーのリスト表示設定
=> [fix] K03012-312 settin form to invisible in PhotoAlbum

app/assets/javascripts/gws/attendance/attendance.js, app/controllers/concerns/gws/attendance/time_card_filter.rb, app/views/gws/attendance/management/time_cards/_menu.html.erb, app/views/gws/attendance/management/time_cards/show.html.erb, app/views/gws/attendance/time_cards/_time_card.html.erb, app/views/gws/memo/export_messages/index.html.erb, app/views/gws/portal/portlets/presence/index.html.erb, app/views/gws/schedule/todo/categories/_form.html.erb, spec/features/gws/attendance/time_card/management/cell_click_spec.rb, spec/features/gws/attendance/time_card/management/search_spec.rb
Fix these isssues:
- unable to edit cell
- cause javascript error at clicking current date cell
- and unable to punch / edit current date cell
- unable to filter by group
=> [fix][gws] time_cart mangament issues

app/assets/javascripts/ss/lib/color.js.erb, app/assets/stylesheets/gws/schedule/_gws.scss, app/assets/stylesheets/ss/_pc_mb.scss, app/controllers/concerns/gws/schedule/plan_filter.rb, app/views/cms/agents/addons/high_contrast_mode/_form.html.erb, app/views/gws/board/categories/_form.html.erb, app/views/gws/circular/categories/_form.html.erb, app/views/gws/contrasts/_form.html.erb, app/views/gws/faq/categories/_form.html.erb, app/views/gws/memo/categories/_form.html.erb, app/views/gws/monitor/categories/_form.html.erb, app/views/gws/notice/categories/_form.html.erb, app/views/gws/qna/categories/_form.html.erb, app/views/gws/report/categories/_form.html.erb, app/views/gws/schedule/categories/_form.html.erb, app/views/gws/schedule/holidays/_form.html.erb, app/views/gws/schedule/plans/_form.html.erb, app/views/gws/schedule/todo/main/_form.html.erb, app/views/gws/share/categories/_form.html.erb, app/views/gws/survey/categories/_form.html.erb, config/defaults/minicolors_swatches.yml, spec/features/gws/schedule/plans/select_color_spec.rb
* [modify] schedule color select form
* [modify] move color_codes.yml to config/defaults
* [modify] renamed color_codes.yml to minicolors_swatches
=> [modify] gws schedule color select form

.codeclimate.yml
https://docs.codeclimate.com/docs/advanced-configuration#analysis-configuration-versions
=> [modify] codeclimate.yml

app/models/concerns/cms/addon/form/page.rb, app/models/concerns/cms/model/page.rb, app/models/concerns/faq/addon/question.rb, app/models/faq/page.rb, lib/migrations/cms/20210628000000_set_cms_pages_size.rb, spec/lib/migrations/cms/20210628000000_set_cms_pages_size_spec.rb
=> [fix] nil error in new_size_input

app/assets/javascripts/ss/lib/tree_navi.js, app/assets/stylesheets/gws/share/_gws.scss
=> [fix] cms: refresh button class

app/controllers/gws/discussion/forums_controller.rb
=> [fix][gws] #3576 discussion_forum: index order

app/jobs/sys/site_import/contents.rb, app/models/concerns/cms/model/node.rb
(cherry picked from commit 1c4ec6bddccacf4d18b3d46cfe8c73f6fe22cc3d)
=> [modify] cms site import: invalid remove_files_recursively

app/controllers/faq/agents/nodes/search_controller.rb, app/views/faq/agents/nodes/search/index.html.erb
(cherry picked from commit 35a1918d685c0f5456019a229a50d942f5cc229d)
=> [modify] faq search : category_ids support

public/assets/js/ckeditor/config.js
(cherry picked from commit 0e5107a13af1dda89eb5def2c6cb5449a33b4481)
=> [modify] public assets js ckeditor config fontSize_style

app/controllers/cms/agents/tasks/nodes_controller.rb
=> [fix] fix: generate node for_member_enabled

app/mailers/gws/memo/mailer.rb, app/mailers/webmail/mailer.rb, app/models/concerns/ss/model/address.rb, app/models/concerns/ss/model/user.rb, app/models/concerns/webmail/mail/message.rb, app/models/webmail/imap/base.rb, app/models/webmail/mail.rb, lib/webmail/converter.rb, spec/lib/webmail/converter_spec.rb, spec/models/webmail/user_extension_spec.rb
case1: name(comment) <email>
case2: name(comment <email>
=> [fix] webmail address

lib/migrations/facility/20220824000000_search_cache.rb, lib/tasks/facility/page.rake, spec/lib/migrations/facility/20220824000000_search_cache_spec.rb
* [add] facility task
* [add] migration
Co-authored-by: tany <tanizawa@web-tips.co.jp>
=> [fix] facility map_points migration

app/controllers/concerns/cms/page_filter.rb, app/views/workflow/agents/addons/approver/_form.html.erb, spec/features/workflow/save_as_branch_spec.rb
* [fix] close page on branch
* [modify] spec
=> [fix] close page on branch (#33)

app/assets/javascripts/gws/schedule/lib/calendar_transition.js, app/assets/javascripts/ss/lib/ajax_file.js, app/assets/javascripts/ss/lib/base.js.erb, app/assets/javascripts/ss/lib/search_ui.js, app/assets/stylesheets/gws/schedule/_gws.scss, app/controllers/gws/apis/facilities_controller.rb, app/controllers/gws/schedule/search/reservations_controller.rb, app/controllers/gws/schedule/search/times_controller.rb, app/models/concerns/gws/addon/reminder.rb, app/models/concerns/gws/schedule/calendar_format.rb, app/models/gws/facility/item.rb, app/models/gws/schedule/plan_search.rb, app/views/gws/agents/addons/reminder/_form.html.erb, app/views/gws/agents/addons/reminder/_show.html.erb, app/views/gws/apis/facilities/index.html.erb, app/views/gws/facility/items/_form.html.erb, app/views/gws/schedule/search/reservations/index.html.erb, app/views/gws/schedule/search/times/_search.html.erb, app/views/gws/schedule/search/times/index.html.erb, app/views/ss/crud/ajax_files/index.html.erb, config/defaults/ss.yml, spec/features/gws/schedule/plans/reminder_spec.rb, spec/features/gws/schedule/search/times_spec.rb
[[fix] gws schedule search times member plan (48)](https://github.com/shirasagi/shirasagi/pull/4686/commits/56d74bd661acd0886c9bc04ab65af4a35b203dfb)
[[modify] gws agents addon reminder interval (53)](https://github.com/shirasagi/shirasagi/pull/4686/commits/0accbd33a669f8b3fe8b944780cd7aab1f8c4720)
[[modify] gws agents addon reminder rendetItems (39)](https://github.com/shirasagi/shirasagi/pull/4686/commits/e6962ebf397daf41599cbad7dc73cc06f81519eb)
[[fix] ss lib search_ui deselect (33)](https://github.com/shirasagi/shirasagi/pull/4686/commits/49a8fd3f307dedae2bb29b20035d3c3a1dc491ca)
[[modify] gws facility item validate_minutes_limit (31)](https://github.com/shirasagi/shirasagi/pull/4686/commits/bc283ec0b3b166cb2f1ce9b7be533474694135a8)
[[fix] gws agents addons reminder _show …
=> [fix] gws schedule some issues

app/views/ezine/agents/addons/body/_form.html.erb, app/views/ezine/agents/addons/body/_show.html.erb, db/seeds/cms/contents/facility.rb
delete '#html' because html editing isn't supported now by #3762
=> [fix][ezine] demo seeds

README.md
=> [modify]update_readme.md

app/controllers/cms/agents/parts/node2_controller.rb, app/controllers/concerns/cms/part_filter/view.rb, app/helpers/cms/list_helper.rb, spec/features/article/agents/parts/rendering_content_spec.rb, spec/features/cms/agents/parts/node2_spec.rb, spec/features/cms/agents/parts/page/rendering_content_spec.rb
within liquid template through `page` or `node` respectively
=> [modify] able to get rendering page or node

app/controllers/chat/agents/nodes/bot_controller.rb, db/seeds/demo/contents/chat.rb, spec/requests/chat/agents/nodes/bot_spec.rb
This commit also fixes an error on responding answers in chat-bot.
=> [fixup] able to get rendering page or node

Gemfile, Gemfile.lock, app/models/concerns/cms/addon/twitter_poster.rb, config/locales/ss/en.yml, config/locales/ss/ja.yml, spec/features/cms/sns_post/twitter/approval_spec.rb, spec/features/cms/sns_post/twitter/basic_spec.rb, spec/features/cms/sns_post/twitter/merge_spec.rb, spec/features/cms/sns_post/twitter/release_page_spec.rb, spec/support/cms/twitter_poster.rb
Also use gem "x" for api version 2.0.
=> [modify] use gem "x" for replacing gem "twitter"

app/models/gws/column/number_field.rb, app/models/ss.rb, app/views/gws/agents/columns/number_field/_column_form.html.erb, spec/features/gws/survey/custom_text_field_spec.rb, spec/features/gws/survey/number_field_spec.rb
* [modify] trim ".0" of decimal value
* [add] numeric like field but more generic
=> [modify][gws] trim decimal string ".0" of number field

app/jobs/gws/reload_site_usage_job.rb, app/jobs/inquiry/delete_inquiry_temp_files_job.rb, app/jobs/ss/cleanup_file_store_cache_job.rb, app/jobs/ss/delete_access_tokens_job.rb, app/jobs/ss/delete_download_files_job.rb, app/jobs/ss/delete_empty_directories_job.rb, app/jobs/ss/delete_sso_tokens_job.rb, config/locales/gws/en.yml, config/locales/gws/ja.yml, config/locales/inquiry/ja.yml, config/locales/ss/en.yml, config/locales/ss/ja.yml, lib/tasks/gws/group.rake, lib/tasks/inquiry/delete_inquiry_temp_files.rake, lib/tasks/ss/daily.rake, lib/tasks/ss/delete_access_tokens.rake, lib/tasks/ss/delete_download_files.rake, lib/tasks/ss/delete_empty_directories.rake, lib/tasks/ss/delete_file_store_cache.rake
To investigate its performance
=> [modify] convert task to job to record its start / end timestamp

app/models/concerns/ss/model/user.rb
also able to search with tel or tel_ext.
=> [modify] able to search with organization_uid

app/assets/stylesheets/ss/_pc_mb.scss, app/views/cms/pages/index.html.erb, config/locales/ss/en.yml, config/locales/ss/ja.yml, spec/features/article/pages/basic_crud_spec.rb
-> implemented source code to show publish end date in index_wait_close action. 
-> added css class .close_date with color red.
-> added spec to check if item has close date and the close_date section is present in index_close_wait. 
-> added localization keys for close_date.
=> Issue 5119:

app/controllers/concerns/ss/captcha_filter.rb, config/locales/inquiry/ja.yml, spec/features/inquiry/agents/parts/feedback_spec.rb
-> stopping user to enter double width input.
=> Issue: 5240:

app/models/chorg.rb, config/application.rb, spec/models/cms/column/value/url_field2_spec.rb, spec/validators/sys/trusted_url_validator_spec.rb
using "Thread.current" have some security considerations.
=> [modify] use ActiveSupport::CurrentAttributes instead of "Thread.current"

app/controllers/gws/schedule/facility_plans_controller.rb, app/models/concerns/gws/addon/facility/default_member_setting.rb, app/models/concerns/gws/addon/import/facility/item.rb, app/models/gws/facility/item.rb, app/views/gws/agents/addons/facility/default_member_setting/_form.html.erb, app/views/gws/agents/addons/facility/default_member_setting/_show.html.erb, config/locales/gws/facility/en.yml, config/locales/gws/facility/ja.yml, spec/features/gws/schedule/facility_plans/default_members_spec.rb
* [order] (19) 設備予約 : 初期設定のユーザー
* [modify] import
=> [modify] gws/schedule : facility plan's default member

app/models/ss/captcha.rb, bin/extract_pdf_base64.rb
see: https://github.com/minimagick/minimagick/releases/tag/v5.0.0
=> [modify] use "MiniMagick.convert" instead of "MiniMagick::Tool::Convert.new"

config/initializers/action_view.rb, config/initializers/sanitize.rb
=> [modify] compatibility of #sanitize before rails 7.1

app/models/cms/line/area.rb, app/models/cms/line/richmenu/menu.rb, app/models/concerns/cms/addon/line/area.rb, app/views/cms/agents/addons/line/richmenu/area/_crop.html.erb, app/views/cms/agents/addons/line/service/area/_crop.html.erb, spec/factories/cms/line/richmenu/group.rb, spec/factories/cms/line/richmenu/menu.rb, spec/features/cms/line/richmenu/menus_spec.rb
* [fix] cms/line : edit richmenu
* [add] spec
* rubocop issues
=> [fix] cms/line : edit richmenu

app/components/cms/nodes_tree_component.rb
以下の追加修正
https://github.com/shirasagi/shirasagi/pull/5459
=> [fix] cms/nodes_tree_component : folders cache_key

app/assets/javascripts/map/reference.js, app/views/cms/agents/columns/main/_base.html.erb
=> [fix] javascripts/map/reference : unable to select column name

app/jobs/concerns/ss/trash_purge/base_job.rb, app/models/concerns/gws/addon/system/group_setting.rb, app/models/concerns/ss/addon/trash_setting.rb, app/models/ss.rb, spec/features/history/cms/trashes_spec.rb, spec/models/ss/parse_threshold_spec.rb
also fix typo "DEFAULT_THRESHOLD_YEARS.days"
=> [modify] refactor trash threshold

app/controllers/concerns/cms/public_filter/part_cache.rb
issue: #5493
先日、ajax part のコントローラーの性能を収集できるように改変した。
この改変によりキャッシュが有効になったパーツで 500 エラーが発生するようになった。
キャッシュが有効になったパーツでもコントローラーの性能を収集できるようにした。
この修正により、ajax part のキャッシュにヒットした場合 "cms/puiblic#ajax_part" が nginx のログに記録されるようになる。
=> [fixup] ajax part support for controller performance (#5493)

app/jobs/cms/generation_report_create_job.rb, app/models/cms/generation_report/title.rb, app/views/cms/generation_report/aggregations/index.html.erb, app/views/cms/generation_report/histories/index.html.erb, app/views/cms/generation_report/histories/show.html.erb, config/locales/cms/ja.yml, spec/jobs/cms/generation_report_create_job/generation_is_running_spec.rb
issue: n/a
- 処理開始日時と処理終了日時とをレポートに保存
- レポートのタイトルを、レポート表示時に表示
=> [CMS] 書き出し性能レポートの改善

app/assets/javascripts/cms/public.js.erb, app/assets/javascripts/ss/lib/base.js.erb, app/models/recommend.rb, app/models/recommend/history/log.rb, spec/features/cms/agents/parts/page/part_cache_spec.rb, spec/features/cms/line/statistics/download_spec.rb, spec/features/gws/histories_spec.rb, spec/support/ss/js_support.rb
issue: n/a
indexの設定変更
- TTLインデックスを明示的に付与。
- path については正規表現を用いた `$nin` によるマッチングのため、index を作成しても効果がないと判断。コメントアウトした。
=> [modify][recommend] index adjustment

app/components/cms/tree_category_component.rb, spec/components/cms/tree_category_component/item_name_spec.rb
issue: #xxxx
カテゴリーのキャッシュ化により発生した不具合の修正
=> [fix] cms/tree_category_component : item_name

app/controllers/chat/agents/parts/bot_controller.rb, app/controllers/cms/agents/parts/calendar_nav_controller.rb, app/controllers/cms/agents/parts/monthly_nav_controller.rb, app/controllers/image_map/agents/parts/page_controller.rb, app/models/event/part.rb, app/views/ckan/agents/nodes/page/index.html.erb, app/views/ckan/agents/parts/page/index.erb, spec/factories/article/parts.rb, spec/factories/chat/parts.rb, spec/factories/ckan/parts.rb, spec/factories/cms/parts.rb, spec/factories/event/parts.rb, spec/factories/image_map/parts.rb, spec/factories/inquiry/parts.rb, spec/factories/member/parts.rb, spec/features/member/agents/nodes/bookmark_spec.rb, spec/requests/cms/agents/parts/ajax_access_spec.rb
issue: n/a
チャットボットパーツの動的表示を有効にすると 406 エラーが発生する。
この問題の修正。
=> [cms] ajax mode support to chat bot part

app/assets/javascripts/chat/lib/bot.js, app/controllers/chat/agents/nodes/bot_controller.rb, app/controllers/concerns/translate/public_filter.rb, app/views/chat/agents/nodes/bot/_index.html.erb, lib/translate/json_converter/chat_bot.rb, spec/features/translate/chat_bot_spec.rb
issue: n/a
CMS自動翻訳時にチャットボットの応答も自動翻訳する修正
=> [wip][modify] chat/bot : cms translate support

app/controllers/gws/memo/list_messages_controller.rb, app/models/gws/memo/list_message.rb, spec/features/gws/memo/list_messages/basic_spec.rb, spec/features/gws/memo/list_messages/reply_spec.rb
issue: #xxxx
リストから送信したメッセージを「返信する」した際のユーザーを修正
=> [fix] gws/memo : list_messages reply user

app/controllers/cms/agents/nodes/photo_album_controller.rb, app/controllers/cms/agents/tasks/node/photo_albums_controller.rb, app/controllers/concerns/cms/node_filter/list_view.rb, app/models/cms/file_search_service.rb, config/environments/development.rb, spec/jobs/cms/node/generate_job/photo_album_spec.rb
issue: n/a
写真一覧フォルダーの書き出しの高速化
ページ一覧書き出し（高速化済み）の仕組みを流用して高速化
=> [modify][cms] photo album generation improvement

app/controllers/history/cms/backups_controller.rb, app/controllers/workflow/frames/branches_controller.rb, app/models/concerns/history/addon/backup.rb, app/models/concerns/history/model/data.rb, app/models/concerns/workflow/addon/branch.rb, app/models/history/backup.rb, app/models/workflow/branch_creation_service.rb, app/views/history/agents/addons/backup/_show.html.erb, config/locales/history/en.yml, config/locales/history/ja.yml, lib/migrations/cms/20250310000000_history_data.rb, spec/features/cms/pages/change_state_all_spec.rb, spec/features/workflow/branch_spec.rb, spec/lib/migrations/cms/20250310000000_history_data_spec.rb, spec/models/article/page/new_clone/basic_page_spec.rb
issue: n/a
差し替えページの更新履歴を、差し替えページの公開・承認時に、親ページへ転送。
差し替えページの更新履歴を、差し替えページの公開・承認後は、親ページの更新履歴で確認することができる。
=> [modify][cms] branch history improvements

app/assets/javascripts/chat/lib/bot.js, app/controllers/concerns/translate/public_filter.rb, app/views/chat/agents/nodes/bot/_index.html.erb, lib/translate/converter.rb, spec/features/translate/ajax_part_spec.rb, spec/features/translate/chat_bot_spec.rb
issue: n/a
#5566 で問題がある箇所の追加修正
=> [fixup] chat/bot : cms translate support

app/models/concerns/opendata/resource/report_model.rb, app/models/opendata/resource_bulk_download_history.rb, app/models/opendata/resource_dataset_download_history.rb, app/models/opendata/resource_download_history.rb
=> [modify][opendata] add db indexes

app/jobs/application_job.rb, app/models/job.rb, spec/models/job/purge_old_job_logs_by_find_spec.rb, spec/models/job/purge_old_job_logs_spec.rb
issue: n/a
古いジョブログを find コマンドを用いて入念に削除するようにした。
=> [modify] purge old job logs with command "find"

app/models/concerns/inquiry/addon/kintone_app/answer.rb, app/models/concerns/inquiry/addon/kintone_app/setting.rb, app/views/inquiry/agents/addons/kintone_app/setting/_form.html.erb, app/views/inquiry/agents/addons/kintone_app/setting/_show.html.erb, config/locales/inquiry/ja.yml, spec/features/inquiry/agents/nodes/form/kintone_app_spec.rb
issue: n/a
お問い合わせフォームとキントーン連携の拡張
リモートIPとユーザーエージェントを連携可能に
=> [modify] inquiry : kintone_app remote_ip and user_agent

.github/workflows/ruby-3.1.yml, .github/workflows/ruby.yml, README.md
Coverallsを削除し、CIテストが正常に動作するようにしました。
=> CIテスト（Coverallsの削除）

app/models/concerns/history/addon/backup.rb, app/models/concerns/history/model/data.rb
更新履歴に次の情報を保存するように変更
- ホスト情報として
- ホスト名
- プロセスID
- ホストのIPアドレス
- リクエスト情報として
- セッションID
- リクエストID
- メソッド（HTTPメソッド；デコード済みのもの）
- コントローラー名
- コントローラーのアクション
=> [cms] 更新履歴に実行ホスト情報とリクエスト情報とを記録

app/assets/javascripts/board/lib/map.js, app/assets/javascripts/map/openlayers/map.js.erb, app/assets/stylesheets/map/_public.scss, app/assets/stylesheets/ss/_pc_mb.scss
Openlayers地図ポップアップの閉じるボタンのアクセシビリティ改善
- Openlayers地図ポップアップの閉じるボタンをボタンタグに変更
- CSS変更
=> [fix]map-marker-popup-close-btn

app/assets/javascripts/cms/public.js.erb, app/javascript/jplayer.scss, db/seeds/demo/files/css/style.css, db/seeds/demo/files/css/style.scss
- 読み上げ機能のボイスコントローラーの閉じるボタンのアクセシビリティ改善
- シーディングデータの修正（閉じるボタンの文字色、ボイスコントローラーの右端が見えなくなっていたのでCSSを調整）
- 読み上げコントローラーの停止ボタンと一時停止ボタンをクリックするとコントローラーが非表示になる問題を修正
=> [modify]accessibility improvements voice close button

app/views/gws/schedule/todo/main/copy.html.erb, config/routes/gws/schedule/routes.rb, spec/features/gws/schedule/todo/basic_crud_spec.rb, spec/features/gws/schedule/todo/manageable_spec.rb
グループウェアToDo
他ユーザーのToDoを複製すると500エラー
=> [fix] gws/schedule/todo : copy

app/assets/javascripts/gws/schedule/lib/multiple_calendar.js, app/assets/stylesheets/gws/schedule/_gws.scss, app/views/gws/portal/portlets/schedule/index.html.erb, app/views/gws/schedule/custom_group_plans/index.html.erb, app/views/gws/schedule/facilities/index.html.erb, app/views/gws/schedule/facilities/print.html.erb, app/views/gws/schedule/group_plans/index.html.erb, app/views/gws/schedule/group_plans/print.html.erb, app/views/gws/schedule/search/users/index.html.erb, spec/features/gws/portal/schedule_portlet/basic_portlet_spec.rb, spec/features/gws/portal/schedule_portlet/multiple_spec.rb
スケジュールのポートレットを複数配置した際に、スケジュールのコントローラーが動作しない問題の修正
=> [fix] gws/schedule : multiple calendar's calendar-controller

app/controllers/concerns/gws/portal/portal_filter.rb, spec/features/gws/portal/hide_menu_portlet_spec.rb
機能（メニュー）自体を非表示にしていたり、権限が無い機能のポートレットが表示されてしまう不具合の修正
=> [fix] gws/portal : show visible and usable portlets

app/models/concerns/ss/model/user.rb, spec/models/gws/user/uid_spec.rb
=> [modify] user_id : allow multiple period

app/assets/stylesheets/cms/preview/main.scss, app/assets/stylesheets/gws/memo/_gws.scss, app/assets/stylesheets/ss/_pc_mb.scss, app/assets/stylesheets/webmail/_ss.scss, stylelint.config.cjs
sass / scss の mixed declarations を修正
参考:
- [Breaking Change: Mixed Declarations](https://sass-lang.com/documentation/breaking-changes/mixed-decls/)
- [SassのMixed Declarationsに対応する](https://qiita.com/sygnas/items/13d89d0a3dd1cec86d99)
=> [fix] sass mixed declarations

app/jobs/concerns/sys/site_copy/cms_nodes.rb, app/jobs/concerns/sys/site_copy/cms_roles.rb, app/jobs/concerns/sys/site_copy/kana_dictionaries.rb, spec/jobs/sys/site_copy_job/kana_dictionary_spec.rb, spec/jobs/sys/site_copy_job/role_spec.rb
=> [fixup] remove permission level completely (#5558)

app/jobs/concerns/ss/sweep_base.rb, app/jobs/ss/task_sweep_job.rb, app/jobs/sys/mail_log_sweep_job.rb, config/defaults/ss.yml, lib/tasks/ss/daily.rake, lib/tasks/sys/task.rake, spec/jobs/sys/task_sweep_job_spec.rb
Sys::MailLog を 14.days で sweep するジョブの追加
ss:daily にタスクを追加
=> [modify] add sys/mail_log_sweep_job

app/views/cms/agents/nodes/site_search/_result.html.erb, app/views/cms/agents/nodes/site_search/index.html.erb
=> [modify] site search

config/environments/production.rb
=> [fixup] Rails 7.2 (#5641)

app/controllers/cms/agents/tasks/pages_controller.rb
=> [modify][cms] puts site and page information to log

app/models/ss/task/performance_collector.rb
=> [fix][cms] performance collector issue

.github/workflows/ruby-3.2.yml, .github/workflows/ruby.yml
MongoDB 8.0 でテストを実行するように修正
7.0 から 8.0 へアップ
=> MongoDB 8.0

.github/workflows/ruby-3.2.yml, .github/workflows/ruby.yml
Node.js 24 を使用して assets を build
Node.js を 20 => 24
=> Node.js 24

Gemfile, Gemfile.lock, bin/puma.service, config/puma.rb, lib/tasks/unicorn.rb
Puma の本番運用への準備
- gem "puma" を development グループから移動
- gem "puma_worker_killer" を追加
- config/puma.rb を収録
- systemd unit ファイルのたたき台を収録
=> Puma and its worker killer

app/assets/stylesheets/cms/_ss.scss, app/views/cms/pages/_change_state.html.erb, config/locales/cms/ja.yml
一括公開・非公開の確認画面にアクセシビリティエラーに関する注意書きを表示
**一括公開操作**
**一括非公開操作**
一括削除画面では表示されません。
=> 一括公開・非公開の確認画面にアクセシビリティエラーに関する注意書きを表示

app/controllers/gws/attendance/apis/management/users_controller.rb, app/models/concerns/ss/model/group.rb, spec/features/gws/attendance/time_card/management/download_spec.rb, spec/models/gws/group_spec.rb
権限「出退勤の管理（自所属）」が与えられたユーザーで、自所属の他ユーザーのタイムカードをダウンロードできない問題の修正
=> [fix][gws][attendance] unable to download time cards by a user granted minimum permissions

app/helpers/map/map_helper.rb, app/models/concerns/ss/addon/map_setting.rb, app/views/map/agents/addons/page/view/index.html.erb, app/views/ss/agents/addons/map_setting/_form.html.erb, app/views/ss/agents/addons/map_setting/_show.html.erb, config/locales/map/ja.yml, config/locales/ss/en.yml, config/locales/ss/ja.yml, lib/migrations/ss/20250602000000_map_setting.rb, spec/features/article/agents/pages/map_spec.rb, spec/features/cms/sites/basic_crud_spec.rb, spec/lib/migrations/ss/20250602000000_map_setting_spec.rb
地図アドオンの公開画面にgooglemapsへのリンクを追加
表示用の設定を追加
=> [modify] cms map : add show googlemaps links

app/assets/stylesheets/ss/_pc_mb.scss, app/assets/stylesheets/ss/_tree.scss
下記のプルリクエストについて、CSSセレクターの後にスペースの追加
関連PR
https://github.com/shirasagi/shirasagi/pull/5685
=> セレクターの後にスペースの追加

app/assets/stylesheets/ss/_pc_mb.scss, app/components/ss/file_view_component.html.erb, app/components/ss/file_view_component.rb
ファイルダイアログで、ユーザーファイルと共有ファイルの場合、ファイル種別を表示。
=> [modify] show type if a file is user file or cms file

db/seeds/gws/contents/workflow2.rb
汎用DBの追加修正。
ワークフロー2のシードの投入に失敗する問題の修正。
=> [fixup^2][gws] 汎用DB (#5672)

app/assets/javascripts/ss/lib/tree_navi.js, app/assets/stylesheets/ss/_pc_mb.scss, app/controllers/cms/apis/node_tree_controller.rb, app/controllers/gws/bookmark/apis/folder_list_controller.rb, app/controllers/gws/notice/apis/folder_list_controller.rb, app/controllers/gws/share/apis/folder_list_controller.rb, app/views/gws/bookmark/apis/folder_list/index.json.jbuilder, app/views/gws/notice/apis/folder_list/index.json.jbuilder, spec/features/gws/bookmark/items/user_folders_spec.rb
SS_TreeNavi の拡張
子要素がない場合に、展開要素をグレーアウト
=> [modify] SS_TreeNavi : child_count

app/controllers/cms/import_controller.rb, app/controllers/cms/node/import_controller.rb
=> [cms] フォルダー取り込みのパンくずを設定

app/jobs/concerns/ss/zip_file_import.rb, app/jobs/opendata/dataset/import_job.rb, app/jobs/sys/site_import_job.rb, app/models/cms/import_job_file.rb, app/models/concerns/cms/reference/files.rb, app/models/concerns/ss/upload_policy.rb, app/models/gws/memo/message_importer.rb, app/models/sitemap/render_service.rb, app/models/webmail/mail_importer.rb, config/locales/gws/tabular/en.yml, config/locales/gws/tabular/ja.yml, lib/ss/zip.rb
汎用DB周りで三回目の修正。
重複コードを削除したり、ロケールを修正したり。
=> [fixup^3][gws] 汎用DB

app/assets/stylesheets/cms/_column.scss, app/assets/stylesheets/ss/_pc_mb.scss, app/views/cms/agents/columns/file_upload/_column_form_v1_image.html.erb, app/views/cms/agents/columns/list/_column_form.html.erb, app/views/cms/agents/columns/youtube/_column_form.html.erb
YouTube項目の設定が増え、編集画面がごちゃごちゃしてきたので調整。
=> [cms] YouTubeカラムのスタイリング調整

app/controllers/fs/files_controller.rb, spec/features/gws/share/files/edit_image_spec.rb, spec/features/opendata/agents/nodes/dataset/resource/preview_graph_spec.rb, spec/support/ss/image_support.rb
CMSサイトが複数ある状況でGWS共有ファイルにアップした画像ファイルを編集できない問題の修正。
=> [fix][gws][share] unable to edit image

app/controllers/gws/affair/attendance/time_cards_controller.rb
=> [fix][gws][affair] type error

app/components/gws/frames/columns/show_component.html.erb, app/components/gws/frames/columns/show_component.rb, app/javascript/application.scss, app/models/concerns/ss/addon/markdown.rb, app/models/gws.rb, app/models/gws/tabular/form.rb, app/models/gws/tabular/space.rb, app/models/gws/tabular/view/base.rb, app/models/gws/workflow2/form/base.rb, config/initializers/sanitize.rb, spec/models/ss/text_to_html_spec.rb
アンケートやレポートの定義の一覧へ遷移時に500エラーが発生する問題の修正
=> [fixup^4][gws] 汎用DB (#5672)

app/models/cms.rb, app/models/uploader/file.rb, app/views/uploader/files/edit.html.erb, app/views/uploader/files/new_files.erb, spec/features/uploader/scss_spec.rb, spec/fixtures/uploader/invalid.scss
アップロードフォルダーにアップロードしたscssファイルにエラーがある場合に、そのエラーを表示するようにした。
=> [fix][uploader] show errors if scss file has errors

app/jobs/concerns/job/cms/copy_nodes/cms_contents.rb, app/jobs/concerns/ss/copy/cms_layouts.rb, app/jobs/concerns/ss/copy/cms_nodes.rb, app/jobs/concerns/ss/copy/cms_pages.rb, app/jobs/concerns/ss/copy/cms_parts.rb, app/jobs/concerns/sys/site_copy/cms_contents.rb, app/models/concerns/ss/relation/file.rb, spec/jobs/sys/site_copy_job/image_map_spec.rb, spec/jobs/sys/site_import/image_map_spec.rb
サイト複製にて ImageMap::Node::Page がコピーできない問題の修正
=> [fix] ss/copy : image_map node

app/models/concerns/article/addon/form_export.rb
=> [modify] cms/form_export validates :form_id

app/jobs/opendata/cms_integration/assoc_job.rb, app/models/concerns/cms/addon/opendata_ref/dataset.rb, config/defaults/opendata.yml, spec/features/article/pages/opendata_ref_realtime_spec.rb
記事投稿連携ジョブを書き出し毎に実行するのを防ぎたい。
yml で書き出し時に実行するかどうか変更できるように修正。
rake コマンドで実行できるように修正。
=> [modify] refactor opendata assoc job

app/models/gws/tabular/initializer.rb
複数台アプリケーションサーバーやアプリケーションサーバーがリサイクルされた際の対応
=> [fixup^7][gws] 汎用DB (#5672)

app/views/garbage/agents/nodes/search/_modal.html.erb, app/views/garbage/agents/nodes/search/index.html.erb
=> [fix] cms garbage : search node label

app/models/gws/tabular/column/lookup_field.rb
ルックアップ列の初期化処理に考慮不足が見つかった。
その修正。
=> [fixup^9][gws] 汎用DB (#5672)

db/seeds/demo/contents/articles.rb, db/seeds/demo/contents/nodes.rb
=> [modify] db seed demo

app/controllers/member/agents/parts/login_controller.rb, app/models/concerns/cms/model/part.rb, app/models/concerns/member/addon/login_link.rb, spec/features/member/agents/parts/login_spec.rb, spec/support/ss/js_support.rb
フォルダー「メンバー/ログイン」にリダイレクトURLがマイページ以外に設定されている場合、
ログインパーツのログインをクリックしても、ログイン画面に遷移しない問題の修正。
=> [fix][member] login path issue

app/models/concerns/cms/addon/form/page.rb, spec/factories/cms/forms.rb, spec/features/article/pages/cms_form/with_entry_form_spec.rb, spec/features/article/pages/preview_editing/youtube_title_button_spec.rb, spec/lib/migrations/cms/20210628000000_set_cms_pages_size_spec.rb, spec/models/article/page/render_html_spec.rb, spec/models/cms/page/render_html_spec.rb
=> [modify][cms] render_html 改善

app/assets/javascripts/cms/preview/main.js.erb, spec/features/article/pages/cms_form/with_entry_form_spec.rb, spec/features/article/pages/cms_form/with_static_form_spec.rb, spec/features/cms/form/columns/headline_spec.rb, spec/features/cms/form_preview/basename_spec.rb, spec/features/cms/form_preview/basic_spec.rb, spec/features/gws/attendance/time_card/management/lock_unlock_spec.rb, spec/features/workflow/edit_requested_page_spec.rb, spec/support/ss/js_support.rb
=> [fix][cms] テスト安定化

app/controllers/contact/apis/contacts_controller.rb, spec/features/contact/apis/pagination_spec.rb
連絡先ダイアログのページネーションが機能することを確認するためにテスト追加。
=> [add][contact] pagination specs on contact dialog

app/views/cms/agents/addons/page_search/_form.html.erb, app/views/cms/agents/addons/site_search/setting/_form.html.erb, app/views/cms/agents/nodes/site_search/article_nodes.html.erb, app/views/guide/agents/addons/question/_form.html.erb, app/views/gws/affair/overtime/aggregate/search_groups/search.html.erb, app/views/gws/affair/overtime/aggregate/search_users/search.html.erb, app/views/gws/agents/addons/affair/duty_hour/_form.html.erb, app/views/gws/agents/addons/affair/duty_notice/_form.html.erb, app/views/gws/agents/addons/affair/holiday/_form.html.erb, app/views/gws/agents/addons/facility/default_member_setting/_form.html.erb, app/views/gws/agents/addons/group/affair_setting/_form.html.erb, app/views/gws/agents/addons/user/affair_setting/_form.html.erb, app/views/gws/agents/addons/workload/member/_form.html.erb, app/views/gws/schedule/user_settings/_form.html.erb, app/views/gws/workflow2/select_forms/_search.html.erb, app/views/sns/frames/temp_files/files/edit.html.erb, app/views/urgency/agents/addons/site_setting/_form.html.erb
=> [fix] duplicated id errors in browser's devtool console

app/views/gws/portal/portlets/todo/index.html.erb, app/views/gws/schedule/todo/main/_show.html.erb, app/views/gws/schedule/todo/main/index.html.erb, app/views/gws/schedule/todo/trashes/index.html.erb, spec/features/gws/schedule/todo/todo_over_spec.rb
ToDoが完了していない状態の時に、期限超過を表示するように変更
=> [modify] gws/todo : todo-over condition

app/assets/javascripts/cms/preview/main.js.erb, app/controllers/cms/preview_controller.rb, app/models/cms/preview_link.rb, app/models/concerns/ss/model/site.rb, config/locales/cms/ja.yml, config/routes/cms/routes_end.rb, spec/features/cms/preview/prevent_external/forms_spec.rb, spec/features/cms/preview/prevent_external/links_spec.rb, spec/fixtures/cms/preview/forms.html, spec/fixtures/cms/preview/links.html, spec/models/cms/preview_link_spec.rb
CMSのプレビューで他サイトへのリンク遷移及びフォーム遷移を停止する。
=> [modify] cms/preview : prevent external prevew

app/jobs/application_job.rb, app/models/job.rb, spec/models/job/purge_old_job_logs_by_find_spec.rb
purge_old_job_logs_by_find の停止
=> [modify] disable purge_old_job_logs_by_find

app/models/concerns/ss/document.rb, spec/models/ss/document_spec.rb
total_bsonsize にて mapReduce を aggregate に置き換える
=> [modify] ss/document : imporve total_bsonsize

app/controllers/application_controller.rb
PUT や DELETE の場合、X-SS-Received-By でメソッドが POST として報告される問題の修正
=> [fix] PUT や DELETE の場合、"X-SS-Received-By" でメソッドが POST として報告される問題の修正

app/models/gws/workflow2/request_service.rb, app/models/gws/workflow2/request_without_approval_service.rb, config/locales/gws/workflow2/en.yml, config/locales/gws/workflow2/ja.yml, spec/models/gws/workflow2/request_service_spec.rb
=> [fix][gws][workflow2] 二重に申請される場合がある（通知が二重に届く場合がある）問題の修正

app/controllers/gws/notice/redirects_controller.rb, app/jobs/gws/elasticsearch/indexer/notice_post_job.rb, app/models/gws/elasticsearch/searcher.rb, app/models/gws/elasticsearch/setting/notice.rb, app/models/gws/notice/post.rb, app/views/gws/notice/readables/_show.html.erb, config/routes/gws/notice/routes.rb, lib/tasks/gws/es.rake, lib/tasks/gws/es.rb, spec/features/gws/elasticsearch/search/notice_spec.rb, spec/jobs/gws/elasticsearch/indexer/notice_post_job_spec.rb, spec/lib/tasks/gws/es/feed_all_notices_spec.rb
=> [add][gws] お知らせの全文検索対応

bin/install.sh
=> Ruby 3.3.9

bin/install.sh
=> Node.js 24.8.0

app/assets/stylesheets/ss/_main_navi.scss
sass コンパイル時の `Deprecation Warning [mixed-decls]` を修正
=> [fix] sass mixed declarations (fixup #5627)

app/models/cms/preview_link.rb, spec/models/cms/preview_link_spec.rb
#5764 の追加修正。
サブサイトの場合 /fs/ にて警告が表示されてしまう。
=> [fixup] cms/preview : prevew /fs/ path
